"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Locale = "en" | "hi" | "bn" | "as" | "ta" | "te" | "mr" | "gu" | "kn" | "ml" | "or" | "pa";

export const SUPPORTED_LOCALES: { code: Locale; name: string; native: string }[] = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "or", name: "Odia", native: "ଓଡ଼িଆ" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
];

export const TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {
    // Navbar
    nav_about: "About",
    nav_digital_id: "Digital ID",
    nav_my_tracking: "My Tracking",
    nav_safety: "Safety Tips",
    nav_emergency: "Emergency SOS",
    nav_faq: "FAQ",
    nav_register: "Register",
    nav_login: "Authority Login",
    nav_dashboard: "Dashboard",
    nav_logout: "Logout",
    // Hero
    hero_badge: "Ministry of Tourism • Government of India",
    hero_title: "Smart Tourist Safety System",
    hero_subtitle: "Real-time safety monitoring, instant voice triage, and secure blockchain tourist identification in Sikkim.",
    hero_register: "Register Tourist ID",
    hero_login: "Authority Access",
    // Stats
    stat_tourists: "Tourists Protected",
    stat_monitoring: "Live Monitoring",
    stat_zones: "Safe Zones Mapped",
    stat_response: "Avg Response Time",
    // Features
    feat_tag: "Key Capabilities",
    feat_title: "Advanced Protection Infrastructure",
    feat_subtitle: "Cutting-edge technology ensuring tourist safety across high-risk mountain terrains.",
    feat_1_title: "Blockchain Digital ID",
    feat_1_desc: "Immutable SHA-256 hash-chain identity verification for tourists without sensitive data exposure.",
    feat_2_title: "AI Voice Triage Assistant",
    feat_2_desc: "Instant 15-second emergency voice triage capturing critical context in 12+ languages.",
    feat_3_title: "Behavioral Digital Twin",
    feat_3_desc: "Real-time risk scoring analyzing spatial crowd density, weather forecasts, and altitude hazards.",
    feat_4_title: "Geofencing & Safe Zones",
    feat_4_desc: "Automated alerts when entering high-risk zones, landslide areas, or off-grid trails.",
    feat_5_title: "Instant Incident Response",
    feat_5_desc: "Direct integration with Sikkim Police & Tourism authority emergency response centers.",
    feat_6_title: "Offline Emergency SMS",
    feat_6_desc: "Fallback satellite and mesh SMS alerts when cellular data connection is unavailable.",
    // How It Works
    hiw_tag: "Simple Process",
    hiw_title: "How It Works",
    hiw_subtitle: "Get protected in 4 quick steps before heading into Sikkim's scenic adventures.",
    hiw_1_title: "1. Create Digital ID",
    hiw_1_desc: "Register basic details to receive your tamper-proof QR code Tourist ID.",
    hiw_2_title: "2. Enable Live Safety",
    hiw_2_desc: "Share your trip itinerary and activate background location monitoring.",
    hiw_3_title: "3. Receive Smart Alerts",
    hiw_3_desc: "Get real-time weather advisories and geofence perimeter warnings.",
    hiw_4_title: "4. One-Tap Emergency SOS",
    hiw_4_desc: "Press SOS for instant automated AI voice triage and rapid rescue dispatch.",
    // Emergency Banner
    emer_banner_title: "In an Emergency Right Now?",
    emer_banner_subtitle: "Press the SOS button or call the national emergency helpline immediately.",
    emer_btn_sos: "Trigger Emergency SOS",
    emer_btn_call: "Call 112 National Helpline",
    // Languages Section
    lang_tag: "Inclusivity",
    lang_title: "Supported Languages",
    lang_subtitle: "Access safety services in your native language. Select any language below to switch immediately.",
    // Digital ID Page
    dig_title: "Digital Tourist ID",
    dig_subtitle: "Blockchain-backed secure identity for seamless verification across check-posts.",
    dig_gen_id: "Generate Digital ID",
    dig_qr_status: "QR Code Status: Active & Verified",
    dig_verified: "Blockchain Verified",
    dig_form_name: "Full Name",
    dig_form_phone: "Mobile Phone Number",
    dig_form_passport: "Government ID / Passport / Aadhaar Number",
    dig_form_submit: "Generate Blockchain ID",
    // My Tracking
    tr_title: "Live GPS & Safety Status",
    tr_subtitle: "Real-time location monitoring and active geofence status.",
    tr_status_active: "Tracking Status: Active",
    tr_status_safe: "Current Zone: Safe Zone (Gangtok Region)",
    tr_geofence_status: "Geofence Status: Inside Permitted Route",
    tr_battery: "Device Battery: 88% (Healthy)",
    // Safety Tips
    saf_title: "Safety Advisories & Guidelines",
    saf_subtitle: "Essential precautions for high-altitude trekking and Sikkim travel.",
    saf_weather_advisory: "Weather Advisory: Heavy rainfall warning in North Sikkim. Travel permits restricted.",
    saf_altitude_tip: "High Altitude Tip: Rest at Gangtok (5,400 ft) before proceeding to Nathula Pass (14,140 ft).",
    saf_emergency_contact: "Local Emergency Command Center: +91 03592 202022",
    // Emergency SOS Page
    sos_title: "Emergency SOS Dispatch",
    sos_subtitle: "Trigger instant automated responder dispatch with AI voice triage.",
    sos_trigger_btn: "PRESS FOR EMERGENCY SOS",
    sos_status_connecting: "Connecting to Emergency Triage Center...",
    sos_helpline_112: "National Emergency Helpline: 112",
    // FAQ Page
    faq_title: "Frequently Asked Questions",
    faq_subtitle: "Find quick answers about tourist safety, digital IDs, and emergency response.",
    faq_search_placeholder: "Search questions...",
    // Auth
    login_title: "Authority Login",
    login_subtitle: "Access the Sikkim Safety Monitoring Dashboard",
    reg_title: "Tourist Registration",
    reg_subtitle: "Create your digital safety profile",
    // Footer
    foot_title: "Sikkim Smart Safety",
    foot_desc: "Ensuring secure, connected, and safe tourism across high-risk terrains using advanced AI digital twins.",
    foot_copy: "Ministry of Tourism, Government of India. All rights reserved.",
    foot_links_header: "Quick Links",
    foot_emer_header: "Emergency Contact"
  },
  hi: {
    // Navbar
    nav_about: "हमारे बारे में",
    nav_digital_id: "डिजिटल आईडी",
    nav_my_tracking: "मेरी ट्रैकिंग",
    nav_safety: "सुरक्षा निर्देश",
    nav_emergency: "आपातकालीन SOS",
    nav_faq: "सामान्य प्रश्न",
    nav_register: "पंजीकरण",
    nav_login: "प्राधिकारी लॉगिन",
    nav_dashboard: "डैशबोर्ड",
    nav_logout: "लॉगआउट",
    // Hero
    hero_badge: "पर्यटन मंत्रालय • भारत सरकार",
    hero_title: "स्मार्ट पर्यटक सुरक्षा प्रणाली",
    hero_subtitle: "सिक्किम में वास्तविक समय सुरक्षा निगरानी, आपातकालीन आवाज ट्राइएज और सुरक्षित ब्लॉकचेन पर्यटक पहचान।",
    hero_register: "पर्यटक आईडी पंजीकरण",
    hero_login: "प्राधिकारी पहुंच",
    // Stats
    stat_tourists: "सुरक्षित पर्यटक",
    stat_monitoring: "लाइव निगरानी",
    stat_zones: "सुरक्षित क्षेत्र",
    stat_response: "औसत प्रतिक्रिया समय",
    // Features
    feat_tag: "मुख्य विशेषताएं",
    feat_title: "उन्नत सुरक्षा ढांचा",
    feat_subtitle: "उच्च जोखिम वाले पहाड़ी क्षेत्रों में पर्यटकों की सुरक्षा सुनिश्चित करने वाली आधुनिक तकनीक।",
    feat_1_title: "ब्लॉकचेन डिजिटल आईडी",
    feat_1_desc: "गोपनीय डेटा उजागर किए बिना SHA-256 हैश-चेन पहचान सत्यापन।",
    feat_2_title: "एआई वॉइस ट्राइएज सहायक",
    feat_2_desc: "12+ भाषाओं में त्वरित 15-सेकंड आपातकालीन आवाज ट्राइएज।",
    feat_3_title: "बिहेवियरल डिजिटल ट्विन",
    feat_3_desc: "भीड़ घनत्व, मौसम पूर्वानुमान और ऊंचाई के खतरों का वास्तविक समय जोखिम विश्लेषण।",
    feat_4_title: "जियोफेंसिंग और सुरक्षित क्षेत्र",
    feat_4_desc: "उच्च जोखिम वाले क्षेत्रों या भूस्खलन संभावित मार्गों पर स्वचालित अलर्ट।",
    feat_5_title: "त्वरित घटना प्रतिक्रिया",
    feat_5_desc: "सिक्किम पुलिस और पर्यटन प्राधिकारी आपातकालीन नियंत्रण केंद्र से सीधा जुड़ाव।",
    feat_6_title: "ऑफलाइन आपातकालीन एसएमएस",
    feat_6_desc: "मोबाइल नेटवर्क न होने पर सैटेलाइट और मेश एसएमएस अलर्ट।",
    // How It Works
    hiw_tag: "सरल प्रक्रिया",
    hiw_title: "यह कैसे काम करता है",
    hiw_subtitle: "सिक्किम की यात्रा पर जाने से पहले 4 आसान चरणों में सुरक्षा प्राप्त करें।",
    hiw_1_title: "1. डिजिटल आईडी बनाएं",
    hiw_1_desc: "अपना सुरक्षित क्यूआर कोड पर्यटक आईडी प्राप्त करने के लिए विवरण दर्ज करें।",
    hiw_2_title: "2. लाइव सुरक्षा सक्षम करें",
    hiw_2_desc: "अपनी यात्रा मार्ग साझा करें और लाइव लोकेशन ट्रैकिंग चालू करें।",
    hiw_3_title: "3. स्मार्ट अलर्ट प्राप्त करें",
    hiw_3_desc: "मौसम संबंधी चेतावनी और जियोफेंस सीमा चेतावनी प्राप्त करें।",
    hiw_4_title: "4. वन-टैप आपातकालीन SOS",
    hiw_4_desc: "स्वचालित एआई वॉइस ट्राइएज और तेजी से बचाव के लिए SOS दबाएं।",
    // Emergency Banner
    emer_banner_title: "क्या आप अभी किसी आपात स्थिति में हैं?",
    emer_banner_subtitle: "तुरंत SOS बटन दबाएं या राष्ट्रीय आपातकालीन हेल्पलाइन पर कॉल करें।",
    emer_btn_sos: "आपातकालीन SOS सक्रिय करें",
    emer_btn_call: "112 राष्ट्रीय हेल्पलाइन पर कॉल करें",
    // Languages Section
    lang_tag: "समावेशिता",
    lang_title: "समर्पित भाषाएं",
    lang_subtitle: "अपनी मातृभाषा में सुरक्षा सेवाओं का उपयोग करें। बदलने के लिए नीचे किसी भी भाषा पर क्लिक करें।",
    // Digital ID Page
    dig_title: "डिजिटल पर्यटक आईडी",
    dig_subtitle: "चेक-पोस्टों पर त्वरित सत्यापन के लिए ब्लॉकचेन-संचालित पहचान।",
    dig_gen_id: "डिजिटल आईडी उत्पन्न करें",
    dig_qr_status: "क्यूआर कोड स्थिति: सक्रिय और सत्यापित",
    dig_verified: "ब्लॉकचेन द्वारा सत्यापित",
    dig_form_name: "पूरा नाम",
    dig_form_phone: "मोबाइल नंबर",
    dig_form_passport: "सरकारी आईडी / पासपोर्ट / आधार संख्या",
    dig_form_submit: "ब्लॉकचेन आईडी बनाएं",
    // My Tracking
    tr_title: "लाइव जीपीएस और सुरक्षा स्थिति",
    tr_subtitle: "वास्तविक समय स्थान निगरानी और सक्रिय जियोफेंस स्थिति।",
    tr_status_active: "ट्रैकिंग स्थिति: सक्रिय",
    tr_status_safe: "वर्तमान क्षेत्र: सुरक्षित क्षेत्र (गंगटोक क्षेत्र)",
    tr_geofence_status: "जियोफेंस स्थिति: अनुमत मार्ग के भीतर",
    tr_battery: "उपकरण बैटरी: 88% (उत्तम)",
    // Safety Tips
    saf_title: "सुरक्षा सलाह और दिशानिर्देश",
    saf_subtitle: "ऊंचाई वाले क्षेत्रों में ट्रेकिंग और सिक्किम यात्रा के लिए आवश्यक सावधानियां।",
    saf_weather_advisory: "मौसम सलाह: उत्तरी सिक्किम में भारी बारिश की चेतावनी। परमिट सीमित हैं।",
    saf_altitude_tip: "उच्च ऊंचाई टिप: नाथुला पास जाने से पहले गंगटोक (5,400 फीट) में विश्राम करें।",
    saf_emergency_contact: "स्थानीय आपातकालीन कमान केंद्र: +91 03592 202022",
    // Emergency SOS Page
    sos_title: "आपातकालीन SOS प्रेषण",
    sos_subtitle: "एआई आवाज ट्राइएज के साथ तुरंत सहायता प्राप्त करें।",
    sos_trigger_btn: "आपातकालीन SOS के लिए दबाएं",
    sos_status_connecting: "आपातकालीन ट्राइएज केंद्र से जुड़ रहा है...",
    sos_helpline_112: "राष्ट्रीय आपातकालीन हेल्पलाइन: 112",
    // FAQ Page
    faq_title: "अक्सर पूछे जाने वाले प्रश्न",
    faq_subtitle: "पर्यटक सुरक्षा, डिजिटल आईडी और आपातकालीन सहायता के बारे में उत्तर पाएं।",
    faq_search_placeholder: "प्रश्न खोजें...",
    // Auth
    login_title: "प्राधिकारी लॉगिन",
    login_subtitle: "सिक्किम सुरक्षा निगरानी डैशबोर्ड में प्रवेश करें",
    reg_title: "पर्यटक पंजीकरण",
    reg_subtitle: "अपनी डिजिटल सुरक्षा प्रोफ़ाइल बनाएं",
    // Footer
    foot_title: "सिक्किम स्मार्ट सुरक्षा",
    foot_desc: "उन्नत एआई डिजिटल ट्विन्स का उपयोग करके सभी उच्च जोखिम वाले क्षेत्रों में सुरक्षित पर्यटन सुनिश्चित करना।",
    foot_copy: "पर्यटन मंत्रालय, भारत सरकार। सर्वाधिकार सुरक्षित।",
    foot_links_header: "त्वरित लिंक",
    foot_emer_header: "आपातकालीन संपर्क"
  },
  bn: {
    // Navbar
    nav_about: "আমাদের সম্পর্কে",
    nav_digital_id: "ডিজিটাল আইডি",
    nav_my_tracking: "আমার ট্র্যাকিং",
    nav_safety: "নিরাপত্তা টিপস",
    nav_emergency: "জরুরি SOS",
    nav_faq: "জিজ্ঞাসাবাদ",
    nav_register: "নিবন্ধন",
    nav_login: "কর্তৃপক্ষ লগইন",
    nav_dashboard: "ড্যাশবোর্ড",
    nav_logout: "লগআউট",
    // Hero
    hero_badge: "পর্যটন মন্ত্রক • ভারত সরকার",
    hero_title: "স্মার্ট পর্যটক নিরাপত্তা ব্যবস্থা",
    hero_subtitle: "সিকিমে রিয়েল-টাইম নিরাপত্তা পর্যবেক্ষণ, জরুরি ভয়েস ট্রায়াজ এবং নিরাপদ ব্লকচেইন পর্যটক সনাক্তকরণ।",
    hero_register: "পর্যটক আইডি নিবন্ধন",
    hero_login: "কর্তৃপক্ষ প্রবেশ",
    // Stats
    stat_tourists: "সুরক্ষিত পর্যটক",
    stat_monitoring: "লাইভ পর্যবেক্ষণ",
    stat_zones: "নিরাপদ অঞ্চল",
    stat_response: "গড় সাড়া সময়",
    // Features
    feat_tag: "প্রধান বৈশিষ্ট্যসমূহ",
    feat_title: "উন্নত সুরক্ষা পরিকাঠামো",
    feat_subtitle: "উচ্চ ঝুঁকিপূর্ণ পাহাড়ি অঞ্চলে পর্যটকদের নিরাপত্তা নিশ্চিত করার প্রযুক্তি।",
    feat_1_title: "ব্লকচেইন ডিজিটাল আইডি",
    feat_1_desc: "ব্যক্তিগত তথ্য প্রকাশ না করেই SHA-256 হ্যাশ-চেইন পরিচয় যাচাইকরণ।",
    feat_2_title: "এআই ভয়েস ট্রায়াজ সহকারী",
    feat_2_desc: "১২+ ভাষায় দ্রুত ১৫-সেকেন্ডের জরুরি ভয়েস ট্রায়াজ।",
    feat_3_title: "বিহেভিওরাল ডিজিটাল টুইন",
    feat_3_desc: "জনসংখ্যার ঘনত্ব, আবহাওয়ার পূর্বাভাস এবং উচ্চতার ঝুঁকির রিয়েল-টাইম বিশ্লেষণ।",
    feat_4_title: "জিওফেন্সিং ও নিরাপদ অঞ্চল",
    feat_4_desc: "ঝুঁকিপূর্ণ অঞ্চল বা ভূমিধস প্রবণ রাস্তায় স্বয়ংক্রিয় সতর্কবার্তা।",
    feat_5_title: "দ্রুত জরুরি সাড়া",
    feat_5_desc: "সিকিম পুলিশ ও পর্যটন কর্তৃপক্ষের জরুরি কন্ট্রোল রুমের সাথে সরাসরি সংযোগ।",
    feat_6_title: "অফলাইন জরুরি এসএমএস",
    feat_6_desc: "মোবাইল নেটওয়ার্ক না থাকলে স্যাটেলাইট এবং মেশ এসএমএস অ্যালার্ট।",
    // How It Works
    hiw_tag: "সহজ প্রক্রিয়া",
    hiw_title: "কীভাবে কাজ করে",
    hiw_subtitle: "সিকিম ভ্রমণের আগে ৪টি সহজ ধাপে নিরাপত্তা পান।",
    hiw_1_title: "১. ডিজিটাল আইডি তৈরি করুন",
    hiw_1_desc: "আপনার নিরাপদ ক্যুআর কোড ডিজিটাল আইডি পেতে তথ্য জমা দিন।",
    hiw_2_title: "২. লাইভ সুরক্ষা চালু করুন",
    hiw_2_desc: "আপনার ভ্রমণের রুট শেয়ার করুন এবং লাইভ ট্র্যাকিং অন করুন।",
    hiw_3_title: "৩. স্মার্ট অ্যালার্ট পান",
    hiw_3_desc: "আবহাওয়ার পূর্বাভাস ও জিওফেন্স সতর্কবার্তা পান।",
    hiw_4_title: "৪. ওয়ান-ট্যাপ জরুরি SOS",
    hiw_4_desc: "জরুরি উদ্ধার সহায়তার জন্য SOS বাটন চাপুন।",
    // Emergency Banner
    emer_banner_title: "এখনই জরুরি পরিস্থিতিতে আছেন?",
    emer_banner_subtitle: "অবিলম্বে SOS বোতামটি চাপুন অথবা জাতীয় জরুরি হেল্পলাইনে কল করুন।",
    emer_btn_sos: "জরুরি SOS সক্রিয় করুন",
    emer_btn_call: "১১২ জাতীয় হেল্পলাইনে কল করুন",
    // Languages Section
    lang_tag: "ভাষা ইনক্লুসিভিটি",
    lang_title: "সমর্থিত ভাষাসমূহ",
    lang_subtitle: "আপনার নিজের ভাষায় নিরাপত্তা পরিষেবা পান। ভাষা পরিবর্তন করতে নিচে ক্লিক করুন।",
    // Digital ID Page
    dig_title: "ডিজিটাল পর্যটক আইডি",
    dig_subtitle: "চেক-পোস্টে দ্রুত যাচাইকরণের জন্য ব্লকচেইন চালিত পরিচয়পত্র।",
    dig_gen_id: "ডিজিটাল আইডি তৈরি করুন",
    dig_qr_status: "কিউআর কোড অবস্থা: সক্রিয় ও যাচাইকৃত",
    dig_verified: "ব্লকচেইন দ্বারা যাচাইকৃত",
    dig_form_name: "সম্পূর্ণ নাম",
    dig_form_phone: "মোবাইল নম্বর",
    dig_form_passport: "সরকারি পরিচয়পত্র / পাসপোর্ট / আধার নম্বর",
    dig_form_submit: "ব্লকচেইন আইডি তৈরি করুন",
    // My Tracking
    tr_title: "লাইভ জিপিএস ও নিরাপত্তা অবস্থা",
    tr_subtitle: "রিয়েল-টাইম অবস্থান পর্যবেক্ষণ এবং জিওফেন্স অবস্থা।",
    tr_status_active: "ট্র্যাকিং অবস্থা: সক্রিয়",
    tr_status_safe: "বর্তমান অঞ্চল: নিরাপদ অঞ্চল (গ্যাংটক)",
    tr_geofence_status: "জিওফেন্স অবস্থা: নির্ধারিত রুটের ভেতরে",
    tr_battery: "ডিভাইস ব্যাটারি: ৮৮% (ভাল)",
    // Safety Tips
    saf_title: "নিরাপত্তা নির্দেশিকা",
    saf_subtitle: "উচ্চ পাহাড়ি অঞ্চলে ভ্রমণের সতর্কতামূলক টিপস।",
    saf_weather_advisory: "আবহাওয়া বার্তা: উত্তর সিকিমে ভারী বৃষ্টির সম্ভাবনা। অনুমতি সীমিত।",
    saf_altitude_tip: "উচ্চতার সতর্কবার্তা: নাথুলা পাস যাওয়ার আগে গ্যাংটকে বিশ্রাম নিন।",
    saf_emergency_contact: "স্থানীয় জরুরি কমান্ড সেন্টার: +৯১ ০৩৫৯২ ২০২০২২",
    // Emergency SOS Page
    sos_title: "জরুরি SOS সহায়তা",
    sos_subtitle: "এআই ভয়েস সহায়তার সাথে সাথে দ্রুত উদ্ধার টিম পাঠান।",
    sos_trigger_btn: "জরুরি SOS এর জন্য চাপুন",
    sos_status_connecting: "জরুরি সাড়া কেন্দ্রের সাথে সংযোগ স্থাপন হচ্ছে...",
    sos_helpline_112: "জাতীয় জরুরি হেল্পলাইন: ১১২",
    // FAQ Page
    faq_title: "সাধারণ জিজ্ঞাসাসমূহ",
    faq_subtitle: "পর্যটক নিরাপত্তা ও ডিজিটাল আইডি সংক্রান্ত উত্তর খুঁজুন।",
    faq_search_placeholder: "প্রশ্ন খুঁজুন...",
    // Auth
    login_title: "কর্তৃপক্ষ লগইন",
    login_subtitle: "সিকিম নিরাপত্তা পর্যবেক্ষণ ড্যাশবোর্ডে প্রবেশ করুন",
    reg_title: "পর্যটক নিবন্ধন",
    reg_subtitle: "আপনার ডিজিটাল নিরাপত্তা প্রোফাইল তৈরি করুন",
    // Footer
    foot_title: "সিকিম স্মার্ট নিরাপত্তা",
    foot_desc: "উন্নত এআই ডিজিটাল টুইন ব্যবহার করে পাহাড়ি অঞ্চলে নিরাপদ পর্যটন নিশ্চিত করা।",
    foot_copy: "পর্যটন মন্ত্রক, ভারত সরকার। সর্বস্বত্ব সংরক্ষিত।",
    foot_links_header: "দ্রুত লিঙ্ক",
    foot_emer_header: "জরুরি যোগাযোগ"
  },
  as: {
    // Navbar
    nav_about: "আমাৰ বিষয়ে",
    nav_digital_id: "ডিজিটেল আইডি",
    nav_my_tracking: "মোৰ ট্ৰেকিং",
    nav_safety: "নিৰাপত্তা টিপছ",
    nav_emergency: "জৰুৰীকালীন SOS",
    nav_faq: "প্ৰশ্নোত্তৰ",
    nav_register: "পঞ্জীয়ন",
    nav_login: "কর্তৃপক্ষ লগইন",
    nav_dashboard: "ড্যাশবোর্ড",
    nav_logout: "লগআউট",
    // Hero
    hero_badge: "পৰ্যটন মন্ত্ৰালয় • ভাৰত চৰকাৰ",
    hero_title: "স্মাৰ্ট পৰ্যটক নিৰাপত্তা ব্যৱস্থা",
    hero_subtitle: "চিকিমত ৰিয়েল-টাইম নিৰাপত্তা নিৰীক্ষণ, জৰুৰীকালীন ট্ৰায়াজ আৰু সুৰক্ষিত ব্লকচেইন পৰ্যটক চিনাক্তকৰণ।",
    hero_register: "পৰ্যটক পঞ্জীয়ন",
    hero_login: "কৰ্তৃপক্ষ প্ৰৱেশ",
    // Stats
    stat_tourists: "সুৰক্ষিত পৰ্যটক",
    stat_monitoring: "লাইভ নিৰীক্ষণ",
    stat_zones: "সুৰক্ষিত অঞ্চল",
    stat_response: "গড় সঁহাৰি সময়",
    // Features
    feat_tag: "মুখ্য বৈশিষ্ট্যসমূহ",
    feat_title: "উন্নত নিৰাপত্তা আন্তঃগাঁথনি",
    feat_subtitle: "পাহাৰীয়া অঞ্চলত পৰ্যটকৰ নিৰাপত্তা নিশ্চিত কৰাৰ আধুনিক প্রযুক্তি।",
    feat_1_title: "ব্লকচেইন ডিজিটেল আইডি",
    feat_1_desc: "ব্যক্তিগত তথ্য প্রকাশ নকৰাকৈ SHA-256 চিনাক্তকৰণ।",
    feat_2_title: "এআই ভইচ ট্ৰায়াজ সহায়ক",
    feat_2_desc: "১২+ ভাষাত ১৫-ছেকেণ্ডৰ জৰুৰীকালীন ভইচ ট্ৰায়াজ।",
    feat_3_title: "বিহেভিওৰেল ডিজিটেল টুইন",
    feat_3_desc: "পৰ্যটকৰ ঘনত্ব আৰু বতৰৰ পূর্বাভাসৰ ৰিয়েল-টাইম নিৰীক্ষণ।",
    feat_4_title: "জিওফেন্সিং আৰু সুৰক্ষিত অঞ্চল",
    feat_4_desc: "বিপজ্জনক অঞ্চলৰ স্বয়ংক্ৰিয় সতৰ্কবাৰ্তা।",
    feat_5_title: "ক্ষিপ্ৰ জৰুৰীকালীন সঁহাৰি",
    feat_5_desc: "চিকিম আৰক্ষী আৰু পৰ্যটন প্ৰাধিকৰণৰ জৰুৰী কেন্দ্ৰৰ সৈতে সংযোগ।",
    feat_6_title: "অফলাইন জৰুৰী SMS",
    feat_6_desc: "নেটৱৰ্ক নথকা স্থানত চেটেলাইট আৰু মেছ SMS সতৰ্কতা।",
    // How It Works
    hiw_tag: "সৰল প্ৰক্ৰিয়া",
    hiw_title: "ই কেনেকৈ কাম কৰে",
    hiw_subtitle: "চিকিম ভ্ৰমণৰ পূৰ্বে ৪টা সহজ পদক্ষেপত নিৰাপত্তা লাভ কৰক।",
    hiw_1_title: "১. ডিজিটেল আইডি বনাক",
    hiw_1_desc: "সুৰক্ষিত QR ক’ড পৰ্যটক আইডি পাবলৈ তথ্য প্ৰদান কৰক।",
    hiw_2_title: "২. লাইভ ট্ৰেকিং অন কৰক",
    hiw_2_desc: "আপোনাৰ ভ্ৰমণৰ পথ শ্বেয়াৰ কৰক আৰু ট্ৰেকিং সক্ৰিয় কৰক।",
    hiw_3_title: "৩. স্মাৰ্ট সতৰ্কবাৰ্তা পাওক",
    hiw_3_desc: "বতৰৰ সতৰ্কবাৰ্তা আৰু জিওফেন্স সতৰ্কতা পাওক।",
    hiw_4_title: "৪. জৰুৰীকালীন SOS",
    hiw_4_desc: "জৰুৰী সহায়ৰ বাবে বোতাম টিপক।",
    // Emergency Banner
    emer_banner_title: "আপুনি এতিয়া কিবা জৰুৰী পৰিস্থিতিত আছে নেকি?",
    emer_banner_subtitle: "তাত্কালিকভাৱে SOS বোতাম টিপক বা ৰাষ্ট্ৰীয় হেল্পলাইনত কল কৰক।",
    emer_btn_sos: "জৰুৰীকালীন SOS সক্ৰিয় কৰক",
    emer_btn_call: "১১২ ৰাষ্ট্ৰীয় হেল্পলাইনত কল কৰক",
    // Languages Section
    lang_tag: "ভাষা সমৰ্থন",
    lang_title: "সমৰ্থিত ভাষাসমূহ",
    lang_subtitle: "আপোনাৰ নিজৰ ভাষাত নিৰাপত্তা সেৱা পাওক। সলনি কৰিবলৈ তলত ক্লিক কৰক।",
    // Digital ID Page
    dig_title: "ডিজিটেল পৰ্যটক আইডি",
    dig_subtitle: "চেক-পোষ্টত দ্ৰুত পৰীক্ষাৰ বাবে ব্লকচেইন পৰিচয় পত্ৰ।",
    dig_gen_id: "ডিজিটেল আইডি সৃষ্টি কৰক",
    dig_qr_status: "QR ক’ড স্থিতি: সক্ৰিয় আৰু সত্যাাপিত",
    dig_verified: "ব্লকচেইন দ্বাৰা সত্যাাপিত",
    dig_form_name: "পূৰ্ণ নাম",
    dig_form_phone: "মোবাইল নম্বৰ",
    dig_form_passport: "পৰিচয় পত্ৰ / পাছপ’ৰ্ট / আধাৰ নম্বৰ",
    dig_form_submit: "ব্লকচেইন আইডি প্ৰস্তুত কৰক",
    // My Tracking
    tr_title: "লাইভ GPS আৰু নিৰাপত্তা স্থিতি",
    tr_subtitle: "ৰিয়েল-টাইম স্থান নিৰীক্ষণ আৰু সক্ৰিয় জিওফেন্স স্থিতি।",
    tr_status_active: "ট্ৰেকিং স্থিতি: সক্ৰিয়",
    tr_status_safe: "বৰ্তমান অঞ্চল: সুৰক্ষিত অঞ্চল (গেংটক)",
    tr_geofence_status: "জিওফেন্স স্থিতি: নিৰ্ধাৰিত পথৰ ভিতৰত",
    tr_battery: "ডিভাইছ বেটাৰী: ৮৮%",
    // Safety Tips
    saf_title: "নিৰাপত্তা নিৰ্দেশনা",
    saf_subtitle: "পাহাৰীয়া ভ্ৰমণৰ বাবে প্ৰয়োজনীয় সাৱধানতা।",
    saf_weather_advisory: "বতৰৰ সতৰ্কতা: উত্তৰ চিকিমত প্ৰবল বৰষুণৰ সম্ভাৱনা।",
    saf_altitude_tip: "উচ্চতাৰ সাৱধানতা: নাথুলা পাছলৈ যোৱাৰ পূৰ্বে গেংটকত জিৰণি লওক।",
    saf_emergency_contact: "স্থানীয় জৰুৰী কমাণ্ড চেণ্টাৰ: +৯১ ০৩৫৯২ ২০২০২২",
    // Emergency SOS Page
    sos_title: "জৰুৰীকালীন SOS প্ৰেৰণ",
    sos_subtitle: "এআই ভইচ সহায়ৰ সৈতে দ্ৰুত উদ্ধাৰকাৰী দল প্ৰেৰণ।",
    sos_trigger_btn: "জৰুৰীকালীন SOS ৰ বাবে টিপক",
    sos_status_connecting: "জৰুৰী কেন্দ্ৰৰ সৈতে সংযোগ হৈ আছে...",
    sos_helpline_112: "ৰাষ্ট্ৰীয় জৰুৰী হেল্পলাইন: ১১২",
    // FAQ Page
    faq_title: "সঘনাই সোধা প্ৰশ্নসমূহ",
    faq_subtitle: "নিৰাপত্তা আৰু ডিজিটেল আইডি সম্পৰ্কে উত্তৰ বিচাৰক।",
    faq_search_placeholder: "প্ৰশ্ন বিচাৰক...",
    // Auth
    login_title: "কৰ্তৃপক্ষ লগইন",
    login_subtitle: "চিকিম নিৰাপত্তা ড্যাশবৰ্ডত প্ৰৱেশ কৰক",
    reg_title: "পৰ্যটক পঞ্জীয়ন",
    reg_subtitle: "আপোনাৰ ডিজিটেল নিৰাপত্তা প্ৰফাইল সৃষ্টি কৰক",
    // Footer
    foot_title: "চিকিম স্মাৰ্ট নিৰাপত্তা",
    foot_desc: "উন্নত এআই ব্যৱহাৰ কৰি সকলো বিপদাশংকা থকা অঞ্চলত সুৰক্ষিত পৰ্যটন নিশ্চিত কৰা।",
    foot_copy: "পৰ্যটন মন্ত্ৰালয়, ভাৰত চৰকাৰ। সৰ্বস্বত্ব সংৰক্ষিত।",
    foot_links_header: "দ্ৰুত সংযোগ",
    foot_emer_header: "জৰুৰী যোগাযোগ"
  },
  ta: {
    nav_about: "பற்றி",
    nav_digital_id: "டிஜிட்டல் ஐடி",
    nav_my_tracking: "என் டிராக்கிங்",
    nav_safety: "பாதுகாப்பு குறிப்புகள்",
    nav_emergency: "அவசர SOS",
    nav_faq: "கேள்வி பதில்கள்",
    nav_register: "பதிவு செய்க",
    nav_login: "அதிகாரிகள் உள்நுழைவு",
    nav_dashboard: "டாஷ்போர்டு",
    nav_logout: "வெளியேறு",
    hero_badge: "சுற்றுலா அமைச்சகம் • இந்திய அரசு",
    hero_title: "ஸ்மார்ட் சுற்றுலா பாதுகாப்பு அமைப்பு",
    hero_subtitle: "சிக்கிமில் நேரலை பாதுகாப்பு கண்காணிப்பு மற்றும் பிளாக்செயின் டிஜிட்டல் சுற்றுலா அடையாளம்.",
    hero_register: "சுற்றுலா ஐடி பதிவு",
    hero_login: "அதிகாரிகள் அணுகல்",
    stat_tourists: "பாதுகாக்கப்பட்ட சுற்றுலா பயணிகள்",
    stat_monitoring: "நேரலை கண்காணிப்பு",
    stat_zones: "பாதுகாப்பான மண்டலங்கள்",
    stat_response: "சராசரி பதில் நேரம்",
    feat_tag: "முக்கிய அம்சங்கள்",
    feat_title: "மேம்பட்ட பாதுகாப்பு உள்கட்டமைப்பு",
    feat_subtitle: "சிக்கலான மலைப்பகுதிகளில் சுற்றுலா பயணிகளின் பாதுகாப்பை உறுதி செய்யும் தொழில்நுட்பம்.",
    feat_1_title: "பிளாக்செயின் டிஜிட்டல் ஐடி",
    feat_1_desc: "SHA-256 மூலம் பாதுகாப்பான மற்றும் சரிபார்க்கப்பட்ட டிஜிட்டல் அடையாளம்.",
    feat_2_title: "AI குரல் உதவி",
    feat_2_desc: "12+ மொழிகளில் 15 வினாடி அவசர குரல் உதவி வசதி.",
    feat_3_title: "டிஜிட்டல் ட்வின் ஆபத்து மதிப்பீடு",
    feat_3_desc: "வானிலை மற்றும் ஆபத்து நிலைகளை நேரலையில் கணிக்கும் AI அமைப்பு.",
    feat_4_title: "ஜியோஃபென்சிங் எச்சரிக்கை",
    feat_4_desc: "ஆபத்தான பகுதிகளை அடையும் போது தானியங்கி எச்சரிக்கைகள்.",
    feat_5_title: "உடனடி மீட்பு பதில்",
    feat_5_desc: "சிக்கிம் காவல்துறை மற்றும் அவசர கட்டுப்பாட்டு மையத்துடன் நேரடி இணைப்பு.",
    feat_6_title: "ஆஃப்லைன் SMS எச்சரிக்கை",
    feat_6_desc: "நெட்வொர்க் இல்லாத இடங்களில் சாட்டிலைட் மற்றும் SMS எச்சரிக்கை.",
    hiw_tag: "எளிய செயல்முறை",
    hiw_title: "இது எவ்வாறு செயல்படுகிறது",
    hiw_subtitle: "சிக்கிம் பயணத்திற்கு முன் 4 எளிதான படிகளில் பாதுகாப்பைப் பெறுங்கள்.",
    hiw_1_title: "1. டிஜிட்டல் ஐடி உருவாக்கவும்",
    hiw_1_desc: "உங்கள் பாதுகாப்பான QR குறியீட்டைப் பெற விவரங்களை அளிக்கவும்.",
    hiw_2_title: "2. நேரலை டிராக்கிங்கை இயக்கவும்",
    hiw_2_desc: "உங்கள் பயண வழியைப் பகிர்ந்து நேரலை இருப்பிட கண்காணிப்பைத் தொடங்குங்கள்.",
    hiw_3_title: "3. ஸ்மார்ட் எச்சரிக்கைகளைப் பெறுங்கள்",
    hiw_3_desc: "வானிலை மற்றும் எல்லை எச்சரிக்கைகளை உடனுக்குடன் பெறுங்கள்.",
    hiw_4_title: "4. ஒற்றைத் தொடு அவசர SOS",
    hiw_4_desc: "உடனடி மீட்புக் குழுவை அழைக்க SOS பொத்தானை அழுத்தவும்.",
    emer_banner_title: "இப்போது அவசர நிலையில் உள்ளீர்களா?",
    emer_banner_subtitle: "உடனடியாக SOS பொத்தானை அழுத்தவும் அல்லது தேசிய அவசர எண்ணை அழைக்கவும்.",
    emer_btn_sos: "அவசர SOS ஐ இயக்கு",
    emer_btn_call: "112 தேசிய உதவி எண்ணை அழைக்கவும்",
    lang_tag: "மொழிகள்",
    lang_title: "ஆதரிக்கப்படும் மொழிகள்",
    lang_subtitle: "உங்கள் தாய்மொழியில் பாதுகாப்பு சேவைகளைப் பெறுங்கள். மாற்ற கீழே கிளிக் செய்யவும்.",
    dig_title: "டிஜிட்டல் சுற்றுலா ஐடி",
    dig_subtitle: "சோதனை சாவடிகளில் வேகமான சரிபார்ப்புக்கு பிளாக்செயின் ஐடி.",
    dig_gen_id: "டிஜிட்டல் ஐடியை உருவாக்கவும்",
    dig_qr_status: "QR நிலை: செயலில் உள்ளது & சரிபார்க்கப்பட்டது",
    dig_verified: "பிளாக்செயின் மூலம் சரிபார்க்கப்பட்டது",
    dig_form_name: "முழு பெயர்",
    dig_form_phone: "கைப்பேசி எண்",
    dig_form_passport: "அரசு ஐடி / பாஸ்போர்ட் / ஆதார் எண்",
    dig_form_submit: "பிளாக்செயின் ஐடியை உருவாக்கு",
    tr_title: "நேரலை GPS & பாதுகாப்பு நிலை",
    tr_subtitle: "நேரலை இருப்பிட கண்காணிப்பு மற்றும் ஜியோஃபென்ஸ் நிலை.",
    tr_status_active: "கண்காணிப்பு நிலை: செயலில் உள்ளது",
    tr_status_safe: "தற்போதைய பகுதி: பாதுகாப்பான பகுதி (காங்டாக்)",
    tr_geofence_status: "ஜியோஃபென்ஸ் நிலை: அனுமதிக்கப்பட்ட வழியில்",
    tr_battery: "பேட்டரி அளவு: 88%",
    saf_title: "பாதுகாப்பு ஆலோசனைகள்",
    saf_subtitle: "மலைப்பயணங்களுக்கான அத்தியாவசிய பாதுகாப்பு குறிப்புகள்.",
    saf_weather_advisory: "வானிலை எச்சரிக்கை: வட சிக்கிமில் கனமழை எச்சரிக்கை.",
    saf_altitude_tip: "உயரமான பகுதி குறிப்பு: நாதுலா பாஸ் செல்வதற்கு முன் காங்டாக்கில் ஓய்வெடுக்கவும்.",
    saf_emergency_contact: "உள்ளூர் அவசர கட்டுப்பாட்டு மையம்: +91 03592 202022",
    sos_title: "அவசர SOS அனுப்புதல்",
    sos_subtitle: "AI குரல் உதவியுடன் உடனடி மீட்புக் குழு அனுப்புதல்.",
    sos_trigger_btn: "அவசர SOS க்கு அழுத்தவும்",
    sos_status_connecting: "அவசர மையத்துடன் இணைக்கிறது...",
    sos_helpline_112: "தேசிய அவசர உதவி எண்: 112",
    faq_title: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    faq_subtitle: "பாதுகாப்பு மற்றும் டிஜிட்டல் ஐடி தொடர்பான பதில்களைக் கண்டறியவும்.",
    faq_search_placeholder: "கேள்விகளைத் தேடவும்...",
    login_title: "அதிகாரிகள் உள்நுழைவு",
    login_subtitle: "சிக்கிம் பாதுகாப்பு கண்காணிப்பு டாஷ்போர்டை அணுகவும்",
    reg_title: "சுற்றுலா பயணிகள் பதிவு",
    reg_subtitle: "உங்கள் டிஜிட்டல் பாதுகாப்பு சுயவிவரத்தை உருவாக்கவும்",
    foot_title: "சிக்கிம் ஸ்மார்ட் பாதுகாப்பு",
    foot_desc: "மேம்பட்ட AI தொழில்நுட்பத்தைப் பயன்படுத்தி பாதுகாப்பான சுற்றுலாவை உறுதி செய்தல்.",
    foot_copy: "சுற்றுலா அமைச்சகம், இந்திய அரசு. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    foot_links_header: "விரைவு இணைப்புகள்",
    foot_emer_header: "அவசர தொடர்பு"
  },
  te: {
    nav_about: "గురించి",
    nav_digital_id: "డిజిటల్ ఐడీ",
    nav_my_tracking: "నా ట్రాకింగ్",
    nav_safety: "భద్రతా సూచనలు",
    nav_emergency: "అత్యవసర SOS",
    nav_faq: "తరచుగా అడిగే ప్రశ్నలు",
    nav_register: "నమోదు",
    nav_login: "అధికారుల లాగిన్",
    nav_dashboard: "డాష్‌బోర్డ్",
    nav_logout: "లాగౌట్",
    hero_badge: "పర్యాటక మంత్రిత్వ శాఖ • భారత ప్రభుత్వం",
    hero_title: "స్మార్ట్ పర్యాటక భద్రతా వ్యవస్థ",
    hero_subtitle: "సిక్కింలో ప్రత్యక్ష భద్రతా పర్యవేక్షణ మరియు సురక్షిత బ్లాక్‌చైన్ పర్యాటక గుర్తింపు.",
    hero_register: "పర్యాటక ఐడీ నమోదు",
    hero_login: "అధికారుల ప్రవేశం",
    stat_tourists: "రక్షించబడిన పర్యాటకులు",
    stat_monitoring: "లైవ్ పర్యవేక్షణ",
    stat_zones: "సురక్షిత ప్రాంతాలు",
    stat_response: "సరాసరి ప్రతిస్పందన సమయం",
    feat_tag: "ముఖ్యమైన వివరాలు",
    feat_title: "ముందంజలో ఉన్న భద్రతా సాంకేతికత",
    feat_subtitle: "ప్రమాదకర పర్వత ప్రాంతాల్లో పర్యాటకుల భద్రతను నిర్ధారించే సాంకేతికత.",
    feat_1_title: "బ్లాక్‌చైన్ డిజిటల్ ఐడీ",
    feat_1_desc: "SHA-256 ద్వారా సురక్షిత మరియు ప్రామాణికమైన డిజిటల్ గుర్తింపు.",
    feat_2_title: "AI వాయిస్ సహాయకుడు",
    feat_2_desc: "12+ భాషలలో 15 సెకన్లలో అత్యవసర వాయిస్ సహాయం.",
    feat_3_title: "డిజిటల్ ట్విన్ ప్రమాద అంచనా",
    feat_3_desc: "వాతావరణం మరియు ఎత్తు ఆధారంగా రియల్-టైమ్ ప్రమాద విశ్లేషణ.",
    feat_4_title: "జియోఫెన్సింగ్ హెచ్చరికలు",
    feat_4_desc: "ప్రమాదకర ప్రాంతాలలోకి ప్రవేశించినప్పుడు స్వయంచాలక హెచ్చరికలు.",
    feat_5_title: "తక్షణ రక్షణ స్పందన",
    feat_5_desc: "సిక్కిం పోలీస్ మరియు రక్షణ విభాగాలతో నేరుగా కనెక్ట్ కావడం.",
    feat_6_title: "ఆఫ్‌లైన్ SMS హెచ్చరికలు",
    feat_6_desc: "నెట్‌వర్క్ లేని ప్రదేశాల్లో శాటిలైట్ మరియు మెష్ SMS హెచ్చరికలు.",
    hiw_tag: "సులభమైన విధానం",
    hiw_title: "ఇది ఎలా పనిచేస్తుంది",
    hiw_subtitle: "సిక్కిం ప్రయాణానికి ముందు 4 సులభమైన దశల్లో రక్షణ పొందండి.",
    hiw_1_title: "1. డిజిటల్ ఐడీని సృష్టించండి",
    hiw_1_desc: "మీ సురక్షిత QR కోడ్ ఐడీ పొందడానికి వివరాలు అందించండి.",
    hiw_2_title: "2. లైవ్ ట్రాకింగ్ ప్రారంభించండి",
    hiw_2_desc: "మీ ప్రయాణ మార్గాన్ని పంచుకొని లైవ్ లొకేషన్ ఆన్ చేయండి.",
    hiw_3_title: "3. స్మార్ట్ హెచ్చరికలు పొందండి",
    hiw_3_desc: "వాతావరణ మరియు సరిహద్దు హెచ్చరికలను వెంటనే పొందండి.",
    hiw_4_title: "4. వన్-టాప్ అత్యవసర SOS",
    hiw_4_desc: "తక్షణ సహాయం కోసం SOS బటన్ నొక్కండి.",
    emer_banner_title: "మీరు ప్రస్తుతం అత్యవసర పరిస్థితిలో ఉన్నారా?",
    emer_banner_subtitle: "వెంటనే SOS బటన్ నొక్కండి లేదా జాతీయ అత్యవసర నంబర్‌కు కాల్ చేయండి.",
    emer_btn_sos: "అత్యవసర SOS ని ప్రారంభించండి",
    emer_btn_call: "112 జాతీయ హెల్ప్‌లైన్‌కు కాల్ చేయండి",
    lang_tag: "భాషలు",
    lang_title: "మద్దతు ఉన్న భాషలు",
    lang_subtitle: "మీ మాతృభాషలో భద్రతా సేవలను పొందండి. మార్చడానికి కింద క్లిక్ చేయండి.",
    dig_title: "డిజిటల్ పర్యాటక ఐడీ",
    dig_subtitle: "చెక్‌పోస్టుల వద్ద వేగవంతమైన తనిఖీ కోసం బ్లాక్‌చైన్ ఐడీ.",
    dig_gen_id: "డిజిటల్ ఐడీని సృష్టించండి",
    dig_qr_status: "QR స్థితి: యాక్టివ్ మరియు ప్రామాణీకరించబడింది",
    dig_verified: "బ్లాక్‌చైన్ ద్వారా ధృవీకరించబడింది",
    dig_form_name: "పూర్తి పేరు",
    dig_form_phone: "మొబైల్ సంఖ్య",
    dig_form_passport: "ప్రభుత్వ ఐడీ / పాస్‌పోర్ట్ / ఆధార్ సంఖ్య",
    dig_form_submit: "బ్లాక్‌చైన్ ఐడీని సృష్టించండి",
    tr_title: "లైవ్ GPS & భద్రతా స్థితి",
    tr_subtitle: "రియల్-టైమ్ స్థాన పర్యవేక్షణ మరియు జియోఫెన్స్ స్థితి.",
    tr_status_active: "ట్రాకింగ్ స్థితి: యాక్టివ్",
    tr_status_safe: "ప్రస్తుత ప్రాంతం: సురక్షిత ప్రాంతం (గ్యాంగ్‌టక్)",
    tr_geofence_status: "జియోఫెన్స్ స్థితి: అనుమతించబడిన మార్గంలో ఉంది",
    tr_battery: "బ్యాటరీ స్థాయి: 88%",
    saf_title: "భద్రతా సూచనలు",
    saf_subtitle: "పర్వత ప్రాంతాల ప్రయాణానికి అవసరమైన జాగ్రత్తలు.",
    saf_weather_advisory: "వాతావరణ హెచ్చరిక: ఉత్తర సిక్కింలో భారీ వర్ష సూచన.",
    saf_altitude_tip: "ఎత్తైన ప్రాంతాల సూచన: నాథులా పాస్ వెళ్లే ముందు గ్యాంగ్‌టక్‌లో విశ్రాంతి తీసుకోండి.",
    saf_emergency_contact: "స్థానిక అత్యవసర కమాండ్ సెంటర్: +91 03592 202022",
    sos_title: "అత్యవసర SOS పంపకం",
    sos_subtitle: "AI వాయిస్ సాయంతో తక్షణ రక్షణ బృందాన్ని పంపడం.",
    sos_trigger_btn: "అత్యవసర SOS కోసం నొక్కండి",
    sos_status_connecting: "అత్యవసర కేంద్రానికి కనెక్ట్ అవుతోంది...",
    sos_helpline_112: "జాతీయ అత్యవసర హెల్ప్‌లైన్: 112",
    faq_title: "తరచుగా అడిగే ప్రశ్నలు",
    faq_subtitle: "భద్రత మరియు డిజిటల్ ఐడీలకు సంబంధించిన సమాధానాలు పొందండి.",
    faq_search_placeholder: "ప్రశ్నలను వెతకండి...",
    login_title: "అధికారుల లాగిన్",
    login_subtitle: "సిక్కిం భద్రతా పర్యవేక్షణ డాష్‌బోర్డ్‌ను ప్రవేశించండి",
    reg_title: "పర్యాటకుల నమోదు",
    reg_subtitle: "మీ డిజిటల్ భద్రతా ప్రొఫైల్‌ను సృష్టించండి",
    foot_title: "సిక్కిం స్మార్ట్ భద్రత",
    foot_desc: "అధునాతన AI సాంకేతికతతో సురక్షితమైన పర్యాటకాన్ని నిర్ధారించడం.",
    foot_copy: "పర్యాటక మంత్రిత్వ శాఖ, భారత ప్రభుత్వం. సర్వ హక్కులు రక్షించబడ్డాయి.",
    foot_links_header: "త్వరిత లింకులు",
    foot_emer_header: "అత్యవసర సంప్రదింపు"
  },
  mr: {
    nav_about: "आमच्याबद्दल",
    nav_digital_id: "डिजिटल आयडी",
    nav_my_tracking: "माझे ट्रॅकिंग",
    nav_safety: "सुरक्षा सूचना",
    nav_emergency: "तातडीचे SOS",
    nav_faq: "सतत विचारले जाणारे प्रश्न",
    nav_register: "नोंदणी",
    nav_login: "अधिकारी लॉगिन",
    nav_dashboard: "डॅशबोर्ड",
    nav_logout: "लॉगआउट",
    hero_badge: "पर्यटन मंत्रालय • भारत सरकार",
    hero_title: "स्मार्ट पर्यटक सुरक्षा प्रणाली",
    hero_subtitle: "सिक्किममध्ये रिअल-टाइम सुरक्षा देखरेख, तातडीची व्हॉइस ट्रियाज आणि सुरक्षित ब्लॉकचेन पर्यटक ओळख.",
    hero_register: "पर्यटक आयडी नोंदणी",
    hero_login: "अधिकारी प्रवेश",
    stat_tourists: "सुरक्षित पर्यटक",
    stat_monitoring: "थेट देखरेख",
    stat_zones: "सुरक्षित क्षेत्र",
    stat_response: "सरासरी प्रतिसाद वेळ",
    feat_tag: "मुख्य वैशिष्ट्ये",
    feat_title: "प्रगत सुरक्षा पायाभूत सुविधा",
    feat_subtitle: "दुर्गम डोंगराळ भागात पर्यटकांची सुरक्षा सुनिश्चित करणारे तंत्रज्ञान.",
    feat_1_title: "ब्लॉकचेन डिजिटल आयडी",
    feat_1_desc: "गोपनीय डेटा उघड न करता SHA-256 द्वारे सुरक्षित ओळख पडताळणी.",
    feat_2_title: "AI व्हॉइस असिस्टंट",
    feat_2_desc: "१२+ भाषांमध्ये १५-सेकंदांचा तातडीचा व्हॉइस सहाय्यक.",
    feat_3_title: "डिजिटल ट्विन जोखीम विश्लेषण",
    feat_3_desc: "हवामान आणि गर्दीच्या घनतेचे रिअल-टाइम जोखीम मूल्यमापन.",
    feat_4_title: "जिओफेंसिंग इशारे",
    feat_4_desc: "धोकादायक भागात प्रवेश करताना स्वयंचलित अलर्ट.",
    feat_5_title: "तातडीचा बचाव प्रतिसाद",
    feat_5_desc: "सिक्किम पोलिस आणि नियंत्रण कक्षाशी थेट संपर्क.",
    feat_6_title: "ऑफलाइन SMS अलर्ट",
    feat_6_desc: "नेटवर्क नसताना सॅटेलाइट आणि मेश SMS द्वारे अलर्ट.",
    hiw_tag: "सोपी प्रक्रिया",
    hiw_title: "हे कसे कार्य करते",
    hiw_subtitle: "सिक्किम प्रवासापूर्वी ४ सोप्या पायऱ्यांमध्ये सुरक्षा मिळवा.",
    hiw_1_title: "१. डिजिटल आयडी तयार करा",
    hiw_1_desc: "सुरक्षित QR कोड मिळवण्यासाठी तुमची माहिती नोंदवा.",
    hiw_2_title: "२. थेट ट्रॅकिंग सुरू करा",
    hiw_2_desc: "तुमचा प्रवास मार्ग शेअर करा आणि ट्रॅकिंग चालू करा.",
    hiw_3_title: "३. स्मार्ट इशारे मिळवा",
    hiw_3_desc: "हवामान आणि जिओफेंस इशारे वेळोवेळी मिळवा.",
    hiw_4_title: "४. वन-टॅप तातडीचे SOS",
    hiw_4_desc: "तात्काळ मदतीसाठी SOS बटण दाबा.",
    emer_banner_title: "तुम्ही सध्या कोणत्याही आणीबाणीच्या परिस्थितीत आहात का?",
    emer_banner_subtitle: "तात्काळ SOS बटण दाबा किंवा राष्ट्रीय आपत्कालीन हेल्पलाइनवर कॉल करा.",
    emer_btn_sos: "आणीबाणी SOS सक्रिय करा",
    emer_btn_call: "११२ राष्ट्रीय हेल्पलाइनवर कॉल करा",
    lang_tag: "भाषा",
    lang_title: "समर्थित भाषा",
    lang_subtitle: "तुमच्या मातृभाषेत सुरक्षा सेवा मिळवा. बदलण्यासाठी खाली क्लिक करा.",
    dig_title: "डिजिटल पर्यटक आयडी",
    dig_subtitle: "चेक-पोस्टवर जलद पडताळणीसाठी ब्लॉकचेन ओळखपत्र.",
    dig_gen_id: "डिजिटल आयडी तयार करा",
    dig_qr_status: "QR स्थिती: सक्रिय आणि सत्यापित",
    dig_verified: "ब्लॉकचेन द्वारे सत्यापित",
    dig_form_name: "पूर्ण नाव",
    dig_form_phone: "मोबाईल नंबर",
    dig_form_passport: "सरकारी आयडी / पासपोर्ट / आधार क्रमांक",
    dig_form_submit: "ब्लॉकचेन आयडी बनवा",
    tr_title: "थेट GPS आणि सुरक्षा स्थिती",
    tr_subtitle: "रिअल-टाइम स्थान देखरेख आणि जिओफेंस स्थिती.",
    tr_status_active: "ट्रॅकिंग स्थिती: सक्रिय",
    tr_status_safe: "सध्याचे क्षेत्र: सुरक्षित क्षेत्र (गँगटॉक)",
    tr_geofence_status: "जिओफेंस स्थिती: मंजूर मार्गात",
    tr_battery: "बॅटरी पातळी: ८८%",
    saf_title: "सुरक्षा सूचना",
    saf_subtitle: "डोंगराळ भागातील प्रवासासाठी आवश्यक खबरदारी.",
    saf_weather_advisory: "हवामान इशारा: उत्तर सिक्किममध्ये मुसळधार पावसाची शक्यता.",
    saf_altitude_tip: "उंचावरील टीप: नथुला पासला जाण्यापूर्वी गँगटॉक येथे विश्रांती घ्या.",
    saf_emergency_contact: "स्थानिक आपत्कालीन नियंत्रण केंद्र: +91 03592 202022",
    sos_title: "आपत्कालीन SOS मदत",
    sos_subtitle: "AI व्हॉइस मदतीसह त्वरित बचाव पथक पाठवणे.",
    sos_trigger_btn: "आपत्कालीन SOS साठी दाबा",
    sos_status_connecting: "आपत्कालीन केंद्राशी कनेक्ट होत आहे...",
    sos_helpline_112: "राष्ट्रीय आपत्कालीन हेल्पलाइन: ११२",
    faq_title: "सतत विचारले जाणारे प्रश्न",
    faq_subtitle: "सुरक्षा आणि डिजिटल आयडीशी संबंधित उत्तरे शोधा.",
    faq_search_placeholder: "प्रश्न शोधा...",
    login_title: "अधिकारी लॉगिन",
    login_subtitle: "सिक्किम सुरक्षा देखरेख डॅशबोर्डमध्ये प्रवेश करा",
    reg_title: "पर्यटक नोंदणी",
    reg_subtitle: "तुमची डिजिटल सुरक्षा प्रोफाइल तयार करा",
    foot_title: "सिक्किम स्मार्ट सुरक्षा",
    foot_desc: "प्रगत AI तंत्रज्ञानाचा वापर करून सुरक्षित पर्यटनाची खात्री देणे.",
    foot_copy: "पर्यटन मंत्रालय, भारत सरकार। सर्व हक्क राखीव.",
    foot_links_header: "जलद लिंक्स",
    foot_emer_header: "आपत्कालीन संपर्क"
  },
  gu: {
    nav_about: "અમારા વિશે",
    nav_digital_id: "ડિજિટલ આઈડી",
    nav_my_tracking: "મારું ટ્રેકિંગ",
    nav_safety: "સુરક્ષા ટિપ્સ",
    nav_emergency: "ઇમરજન્સી SOS",
    nav_faq: "પ્રશ્નોત્તરી",
    nav_register: "રજીસ્ટર",
    nav_login: "અધિકારી લોગિન",
    nav_dashboard: "ડેશબોર્ડ",
    nav_logout: "લોગઆઉટ",
    hero_badge: "પ્રવાસન મંત્રાલય • ભારત સરકાર",
    hero_title: "સ્માર્ટ પ્રવાસી સુરક્ષા પ્રણાલી",
    hero_subtitle: "સિક્કિમમાં રીઅલ-ટાઇમ સુરક્ષા મોનિટરિંગ અને સુરક્ષિત બ્લોકચેન આઇડેન્ટિટી.",
    hero_register: "પ્રવાસી આઈડી રજીસ્ટર કરો",
    hero_login: "અધિકારી પ્રવેશ",
    stat_tourists: "સુરક્ષિત પ્રવાસીઓ",
    stat_monitoring: "લાઈવ મોનિટરિંગ",
    stat_zones: "સુરક્ષિત વિસ્તારો",
    stat_response: "સરેરાશ પ્રતિભાવ સમય",
    feat_tag: "મુખ્ય વિશેષતાઓ",
    feat_title: "અદ્યતન સુરક્ષા ઈન્ફ્રાસ્ટ્રક્ચર",
    feat_subtitle: "જોખમી પહાડી વિસ્તારોમાં પ્રવાસીઓની સુરક્ષા સુનિશ્ચિત કરતી ટેકનોલોજી.",
    feat_1_title: "બ્લોકચેન ડિજિટલ આઈડી",
    feat_1_desc: "SHA-256 દ્વારા સુરક્ષિત અને ચકાસાયેલ ડિજિટલ ઓળખ.",
    feat_2_title: "AI વોઇસ અસિસ્ટન્ટ",
    feat_2_desc: "12+ ભાષાઓમાં 15-સેકન્ડની તાત્કાલિક વોઇસ સહાય.",
    feat_3_title: "ડિજિટલ ટ્વિન જોખમ વિશ્લેષણ",
    feat_3_desc: "હવામાન અને ઊંચાઈના જોખમોનું રીઅલ-ટાઇમ મૂલ્યાંકન.",
    feat_4_title: "જિયોફેન્સિંગ ચેતવણીઓ",
    feat_4_desc: "જોખમી વિસ્તારોમાં પ્રવેશતી વખતે સ્વચાલિત એલર્ટ.",
    feat_5_title: "તાત્કાલિક બચાવ પ્રતિભાવ",
    feat_5_desc: "સિક્કિમ પોલીસ અને કંટ્રોલ રૂમ સાથે સીધો સંપર્ક.",
    feat_6_title: "ઓફલાઇન SMS એલર્ટ",
    feat_6_desc: "નેટવર્ક ન હોય ત્યારે સેટેલાઇટ અને મેશ SMS એલર્ટ.",
    hiw_tag: "સરળ પ્રક્રિયા",
    hiw_title: "આ કેવી રીતે કામ કરે છે",
    hiw_subtitle: "સિક્કિમની મુસાફરી પહેલા 4 સરળ પગલાંમાં સુરક્ષા મેળવો.",
    hiw_1_title: "1. ડિજિટલ આઈડી બનાવો",
    hiw_1_desc: "તમારો સુરક્ષિત QR કોડ મેળવવા માટે વિગતો આપો.",
    hiw_2_title: "2. લાઈવ ટ્રેકિંગ ચાલુ કરો",
    hiw_2_desc: "તમારો રૂટ શેર કરો અને લાઈવ લોકેશન ચાલુ કરો.",
    hiw_3_title: "3. સ્માર્ટ એલર્ટ મેળવો",
    hiw_3_desc: "હવામાન અને સીમા ચેતવણીઓ તાત્કાલિક મેળવો.",
    hiw_4_title: "4. વન-ટેપ ઇમરજન્સી SOS",
    hiw_4_desc: "તાત્કાલિક મદદ માટે SOS બટન દબાવો.",
    emer_banner_title: "શું તમે અત્યારે કોઈ કટોકટીમાં છો?",
    emer_banner_subtitle: "તરત જ SOS બટન દબાવો અથવા રાષ્ટ્રીય હેલ્પલાઇન પર કોલ કરો.",
    emer_btn_sos: "ઇમરજન્સી SOS ચાલુ કરો",
    emer_btn_call: "112 રાષ્ટ્રીય હેલ્પલાઇન પર કોલ કરો",
    lang_tag: "ભાષાઓ",
    lang_title: "સપોર્ટેડ ભાષાઓ",
    lang_subtitle: "તમારી માતૃભાષામાં સુરક્ષા સેવાઓ મેળવો. બદલવા માટે નીચે ક્લિક કરો.",
    dig_title: "ડિજિટલ પ્રવાસી આઈડી",
    dig_subtitle: "ચેક-પોસ્ટ પર ઝડપી ચકાસણી માટે બ્લોકચેન ઓળખપત્ર.",
    dig_gen_id: "ડિજિટલ આઈડી બનાવો",
    dig_qr_status: "QR સ્થિતિ: સક્રિય અને ચકાસાયેલ",
    dig_verified: "બ્લોકચેન દ્વારા ચકાસાયેલ",
    dig_form_name: "પૂરું નામ",
    dig_form_phone: "મોબાઇલ નંબર",
    dig_form_passport: "સરકારી આઈડી / પાસપોર્ટ / આધાર નંબર",
    dig_form_submit: "બ્લોકચેન આઈડી બનાવો",
    tr_title: "લાઈવ GPS અને સુરક્ષા સ્થિતિ",
    tr_subtitle: "રીઅલ-ટાઇમ લોકેશન મોનિટરિંગ અને જિયોફેન્સ સ્થિતિ.",
    tr_status_active: "ટ્રેકિંગ સ્થિતિ: સક્રિય",
    tr_status_safe: "વર્તમાન વિસ્તાર: સુરક્ષિત વિસ્તાર (ગેંગટોક)",
    tr_geofence_status: "જિયોફેન્સ સ્થિતિ: મંજૂર રૂટની અંદર",
    tr_battery: "બેટરી લેવલ: 88%",
    saf_title: "સુરક્ષા સૂચનાઓ",
    saf_subtitle: "પહાડી પ્રવાસ માટે જરૂરી સાવચેતીઓ.",
    saf_weather_advisory: "હવામાન ચેતવણી: ઉત્તર સિક્કિમમાં ભારે વરસાદની ચેતવણી.",
    saf_altitude_tip: "ઊંચાઈ ટિપ: નાથુલા પાસ જતા પહેલા ગેંગટોકમાં આરામ કરો.",
    saf_emergency_contact: "સ્થાનિક ઇમરજન્સી કંટ્રોલ સેન્ટર: +91 03592 202022",
    sos_title: "ઇમરજન્સી SOS મોકલો",
    sos_subtitle: "AI વોઇસ મદદ સાથે તાત્કાલિક ટીમ મોકલવી.",
    sos_trigger_btn: "ઇમરજન્સી SOS માટે દબાવો",
    sos_status_connecting: "ઇમરજન્સી સેન્ટર સાથે કનેક્ટ થઈ રહ્યું છે...",
    sos_helpline_112: "રાષ્ટ્રીય ઇમરજન્સી હેલ્પલાઇન: 112",
    faq_title: "વારંવાર પૂછાતા પ્રશ્નો",
    faq_subtitle: "સુરક્ષા અને ડિજિટલ આઈડી અંગેના જવાબો શોધો.",
    faq_search_placeholder: "પ્રશ્નો શોધો...",
    login_title: "અધિકારી લોગિન",
    login_subtitle: "સિક્કિમ સુરક્ષા મોનિટરિંગ ડેશબોર્ડ ખોલો",
    reg_title: "પ્રવાસી રજીસ્ટ્રેશન",
    reg_subtitle: "તમારું ડિજિટલ સુરક્ષા પ્રોફાઇલ બનાવો",
    foot_title: "સિક્કિમ સ્માર્ટ સુરક્ષા",
    foot_desc: "અદ્યતન AI ટેકનોલોજીથી સુરક્ષિત પ્રવાસન સુનિશ્ચિત કરવું.",
    foot_copy: "પ્રવાસન મંત્રાલય, ભારત સરકાર. સર્વાધિકાર સુરક્ષિત.",
    foot_links_header: "ઝડપી લિંક્સ",
    foot_emer_header: "ઇમરજન્સી સંપર્ક"
  },
  kn: {
    nav_about: "ಕುರಿತು",
    nav_digital_id: "ಡಿಜಿಟಲ್ ಐಡಿ",
    nav_my_tracking: "ನನ್ನ ಟ್ರ್ಯಾಕಿಂಗ್",
    nav_safety: "ಸುರಕ್ಷತಾ ಸಲಹೆಗಳು",
    nav_emergency: "ತುರ್ತು SOS",
    nav_faq: "ಪ್ರಶ್ನೋತ್ತರ",
    nav_register: "ನೋಂದಣಿ",
    nav_login: "ಅಧಿಕಾರಿಗಳ ಲಾಗಿನ್",
    nav_dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    nav_logout: "ಲಾಗ್‌ಔಟ್",
    hero_badge: "ಪ್ರವಾಸೋದ್ಯಮ ಸಚಿವಾಲಯ • ಭಾರತ ಸರ್ಕಾರ",
    hero_title: "ಸ್ಮಾರ್ಟ್ ಪ್ರವಾಸಿ ಸುರಕ್ಷತಾ ವ್ಯವಸ್ಥೆ",
    hero_subtitle: "ಸಿಕ್ಕಿಂನಲ್ಲಿ ನೈಜ-ಸಮಯದ ಸುರಕ್ಷತಾ ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ಸುರಕ್ಷಿತ ಬ್ಲಾಕ್‌ಚೈನ್ ಪ್ರವಾಸಿ ಗುರುತು.",
    hero_register: "ಪ್ರವಾಸಿ ಐಡಿ ನೋಂದಾಯಿಸಿ",
    hero_login: "ಅಧಿಕಾರಿಗಳ ಪ್ರವೇಶ",
    stat_tourists: "ಸುರಕ್ಷಿತ ಪ್ರವಾಸಿಗರು",
    stat_monitoring: "ಲೈವ್ ಮೇಲ್ವಿಚಾರಣೆ",
    stat_zones: "ಸುರಕ್ಷಿತ ವಲಯಗಳು",
    stat_response: "ಸರಾಸರಿ ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯ",
    feat_tag: "ಪ್ರಮುಖ ವೈಶಿಷ್ಟ್ಯಗಳು",
    feat_title: "ಸುಧಾರಿತ ಸುರಕ್ಷತಾ ಮೂಲಸೌಕರ್ಯ",
    feat_subtitle: "ಅಪಾಯಕಾರಿ ಪರ್ವತ ಪ್ರದೇಶಗಳಲ್ಲಿ ಪ್ರವಾಸಿಗರ ಸುರಕ್ಷತೆಯನ್ನು ಖಾತ್ರಿಪಡಿಸುವ ತಂತ್ರಜ್ಞಾನ.",
    feat_1_title: "ಬ್ಲಾಕ್‌ಚೈನ್ ಡಿಜಿಟಲ್ ಐಡಿ",
    feat_1_desc: "SHA-256 ಮೂಲಕ ಸುರಕ್ಷಿತ ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ಡಿಜಿಟಲ್ ಗುರುತು.",
    feat_2_title: "AI ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್",
    feat_2_desc: "12+ ಭಾಷೆಗಳಲ್ಲಿ 15 ಸೆಕೆಂಡುಗಳ ತುರ್ತು ಧ್ವನಿ ನೆರವು.",
    feat_3_title: "ಡಿಜಿಟಲ್ ಟ್ವಿನ್ ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ",
    feat_3_desc: "ಹವಾಮಾನ ಮತ್ತು ಎತ್ತರದ ಅಪಾಯಗಳ ನೈಜ-ಸಮಯದ ವಿಶ್ಲೇಷಣೆ.",
    feat_4_title: "ಜಿಯೋಫೆನ್ಸಿಂಗ್ ಎಚ್ಚರಿಕೆಗಳು",
    feat_4_desc: "ಅಪಾಯಕಾರಿ ಪ್ರದೇಶಗಳನ್ನು ಪ್ರವೇಶಿಸಿದಾಗ ಸ್ವಯಂಚಾಲಿತ ಎಚ್ಚರಿಕೆಗಳು.",
    feat_5_title: "ತಕ್ಷಣದ ರಕ್ಷಣಾ ಪ್ರತಿಕ್ರಿಯೆ",
    feat_5_desc: "ಸಿಕ್ಕಿಂ ಪೊಲೀಸ್ ಮತ್ತು ತುರ್ತು ನಿಯಂತ್ರಣ ಕೊಠಡಿಯೊಂದಿಗೆ ನೇರ ಸಂಪರ್ಕ.",
    feat_6_title: "ಆಫ್‌ಲೈನ್ SMS ಎಚ್ಚರಿಕೆ",
    feat_6_desc: "ನೆಟ್‌ವರ್ಕ್ ಇಲ್ಲದಿರುವಾಗ ಸ್ಯಾಟಲೈಟ್ ಮತ್ತು SMS ಎಚ್ಚರಿಕೆಗಳು.",
    hiw_tag: "ಸುಲಭ ಪ್ರಕ್ರಿಯೆ",
    hiw_title: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    hiw_subtitle: "ಸಿಕ್ಕಿಂ ಪ್ರವಾಸಕ್ಕೂ ಮುನ್ನ 4 ಸುಲಭ ಹಂತಗಳಲ್ಲಿ ಸುರಕ್ಷತೆ ಪಡೆಯಿರಿ.",
    hiw_1_title: "1. ಡಿಜಿಟಲ್ ಐಡಿ ರಚಿಸಿ",
    hiw_1_desc: "ನಿಮ್ಮ ಸುರಕ್ಷಿತ QR ಕೋಡ್ ಪಡೆಯಲು ವಿವರಗಳನ್ನು ನೀಡಿ.",
    hiw_2_title: "2. ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್ ಸಕ್ರಿಯಗೊಳಿಸಿ",
    hiw_2_desc: "ನಿಮ್ಮ ಪ್ರಯಾಣದ ಮಾರ್ಗವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ಲೈವ್ ಲೊಕೇಶನ್ ಆನ್ ಮಾಡಿ.",
    hiw_3_title: "3. ಸ್ಮಾರ್ಟ್ ಎಚ್ಚರಿಕೆ ಪಡೆಯಿರಿ",
    hiw_3_desc: "ಹವಾಮಾನ ಮತ್ತು ಗಡಿ ಎಚ್ಚರಿಕೆಗಳನ್ನು ತಕ್ಷಣ ಪಡೆಯಿರಿ.",
    hiw_4_title: "4. ಒನ್-ಟ್ಯಾಪ್ ತುರ್ತು SOS",
    hiw_4_desc: "ತಕ್ಷಣದ ಸಹಾಯಕ್ಕಾಗಿ SOS ಬಟನ್ ಒತ್ತಿ.",
    emer_banner_title: "ನೀವು ಈಗ ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿದ್ದೀರಾ?",
    emer_banner_subtitle: "ತಕ್ಷಣವೇ SOS ಬಟನ್ ಒತ್ತಿ ಅಥವಾ ರಾಷ್ಟ್ರೀಯ ತುರ್ತು ಸಹಾಯವಾಣಿಗೆ ಕರೆ ಮಾಡಿ.",
    emer_btn_sos: "ತುರ್ತು SOS ಸಕ್ರಿಯಗೊಳಿಸಿ",
    emer_btn_call: "112 ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿಗೆ ಕರೆ ಮಾಡಿ",
    lang_tag: "ಭಾಷೆಗಳು",
    lang_title: "ಬೆಂಬಲಿತ ಭಾಷೆಗಳು",
    lang_subtitle: "ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಸುರಕ್ಷತಾ ಸೇವೆಗಳನ್ನು ಪಡೆಯಿರಿ. ಬದಲಾಯಿಸಲು ಕೆಳಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    dig_title: "ಡಿಜಿಟಲ್ ಪ್ರವಾಸಿ ಐಡಿ",
    dig_subtitle: "ಚೆಕ್-ಪೋಸ್ಟ್‌ಗಳಲ್ಲಿ ತ್ವರಿತ ತಪಾಸಣೆಗಾಗಿ ಬ್ಲಾಕ್‌ಚೈನ್ ಐಡಿ.",
    dig_gen_id: "ಡಿಜಿಟಲ್ ಐಡಿ ರಚಿಸಿ",
    dig_qr_status: "QR ಸ್ಥಿತಿ: ಸಕ್ರಿಯವಾಗಿದೆ ಮತ್ತು ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    dig_verified: "ಬ್ಲಾಕ್‌ಚೈನ್‌ನಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    dig_form_name: "ಪೂರ್ಣ ಹೆಸರು",
    dig_form_phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    dig_form_passport: "ಸರ್ಕಾರಿ ಐಡಿ / ಪಾಸ್‌ಪೋರ್ಟ್ / ಆಧಾರ್ ಸಂಖ್ಯೆ",
    dig_form_submit: "ಬ್ಲಾಕ್‌ಚೈನ್ ಐಡಿ ಸೃಷ್ಟಿಸಿ",
    tr_title: "ಲೈವ್ GPS ಮತ್ತು ಸುರಕ್ಷತಾ ಸ್ಥಿತಿ",
    tr_subtitle: "ನೈಜ-ಸಮಯದ ಸ್ಥಳ ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ಜಿಯೋಫೆನ್ಸ್ ಸ್ಥಿತಿ.",
    tr_status_active: "ಟ್ರ್ಯಾಕಿಂಗ್ ಸ್ಥಿತಿ: ಸಕ್ರಿಯ",
    tr_status_safe: "ಪ್ರಸ್ತುತ ವಲಯ: ಸುರಕ್ಷಿತ ವಲಯ (ಗ್ಯಾಂಗ್‌ಟಾಕ್)",
    tr_geofence_status: "ಜಿಯೋಫೆನ್ಸ್ ಸ್ಥಿತಿ: ಅನುಮೋದಿತ ಮಾರ್ಗದಲ್ಲಿ",
    tr_battery: "ಬ್ಯಾಟರಿ ಮಟ್ಟ: 88%",
    saf_title: "ಸುರಕ್ಷತಾ ಮಾರ್ಗಸೂಚಿಗಳು",
    saf_subtitle: "ಪರ್ವತ ಪ್ರವಾಸಕ್ಕೆ ಅಗತ್ಯವಾದ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು.",
    saf_weather_advisory: "ಹವಾಮಾನ ಮುನ್ನೆಚ್ಚರಿಕೆ: ಉತ್ತರ ಸಿಕ್ಕಿಂನಲ್ಲಿ ಭಾರಿ ಮಳೆ ಎಚ್ಚರಿಕೆ.",
    saf_altitude_tip: "ಎತ್ತರದ ಪ್ರದೇಶದ ಸಲಹೆ: ನಾಥುಲಾ ಪಾಸ್‌ಗೆ ಹೋಗುವ ಮುನ್ನ ಗ್ಯಾಂಗ್‌ಟಾಕ್‌ನಲ್ಲಿ ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.",
    saf_emergency_contact: "ಸ್ಥಳೀಯ ತುರ್ತು ಕಮಾಂಡ್ ಸೆಂಟರ್: +91 03592 202022",
    sos_title: "ತುರ್ತು SOS ಕಳುಹಿಸುವಿಕೆ",
    sos_subtitle: "AI ಧ್ವನಿ ನೆರವಿನೊಂದಿಗೆ ತಕ್ಷಣ ರಕ್ಷಣಾ ತಂಡ ಕಳುಹಿಸುವುದು.",
    sos_trigger_btn: "ತುರ್ತು SOS ಗಾಗಿ ಒತ್ತಿ",
    sos_status_connecting: "ತುರ್ತು ಕೇಂದ್ರಕ್ಕೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...",
    sos_helpline_112: "ರಾಷ್ಟ್ರೀಯ ತುರ್ತು ಸಹಾಯವಾಣಿ: 112",
    faq_title: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    faq_subtitle: "ಸುರಕ್ಷತೆ ಮತ್ತು ಡಿಜಿಟಲ್ ಐಡಿ ಕುರಿತು ಉತ್ತರಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.",
    faq_search_placeholder: "ಪ್ರಶ್ನೆಗಳನ್ನು ಹುಡುಕಿ...",
    login_title: "ಅಧಿಕಾರಿಗಳ ಲಾಗಿನ್",
    login_subtitle: "ಸಿಕ್ಕಿಂ ಸುರಕ್ಷತಾ ಮೇಲ್ವಿಚಾರಣಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಿ",
    reg_title: "ಪ್ರವಾಸಿಗರ ನೋಂದಣಿ",
    reg_subtitle: "ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಸುರಕ್ಷತಾ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
    foot_title: "ಸಿಕ್ಕಿಂ ಸ್ಮಾರ್ಟ್ ಸುರಕ್ಷತೆ",
    foot_desc: "ಸುಧಾರಿತ AI ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ಸುರಕ್ಷಿತ ಪ್ರವಾಸೋದ್ಯಮವನ್ನು ಖಚಿತಪಡಿಸುವುದು.",
    foot_copy: "ಪ್ರವಾಸೋದ್ಯಮ ಸಚಿವಾಲಯ, ಭಾರತ ಸರ್ಕಾರ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    foot_links_header: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    foot_emer_header: "ತುರ್ತು ಸಂಪರ್ಕ"
  },
  ml: {
    nav_about: "ಕುറിച്ച്",
    nav_digital_id: "ഡിജിറ്റൽ ഐഡി",
    nav_my_tracking: "എന്റെ ട്രാക്കിംഗ്",
    nav_safety: "സുരക്ഷാ നിർദ്ദേശങ്ങൾ",
    nav_emergency: "അടിയന്തിര SOS",
    nav_faq: "ചോദ്യോത്തരങ്ങൾ",
    nav_register: "രജിസ്റ്റർ ചെയ്യുക",
    nav_login: "അതോറിറ്റി ലോഗിൻ",
    nav_dashboard: "ഡാഷ്‌ബോർഡ്",
    nav_logout: "ലോഗ് ഔട്ട്",
    hero_badge: "ടൂറിസം മന്ത്രാലയം • ഭാരത സർക്കാർ",
    hero_title: "സ്മാർട്ട് ടൂറിസ്റ്റ് സുരക്ഷാ സംവിധാനം",
    hero_subtitle: "സിക്കിമിൽ തത്സമയ സുരക്ഷാ നിരീക്ഷണവും സുരക്ഷിത ബ്ലോക്ക്ചെയിൻ ഡിജിറ്റൽ ഐഡിയും.",
    hero_register: "ടൂറിസ്റ്റ് ഐഡി രജിസ്റ്റർ ചെയ്യുക",
    hero_login: "അതോറിറ്റി പ്രവേശനം",
    stat_tourists: "സുരക്ഷിതരാക്കിയ ടൂറിസ്റ്റുകൾ",
    stat_monitoring: "ലൈവ് നിരീക്ഷണം",
    stat_zones: "സുരക്ഷിത മേഖലകൾ",
    stat_response: "ശരാശരി പ്രതികരണ സമയം",
    feat_tag: "പ്രധാന സവിശേഷതകൾ",
    feat_title: "അത്യാധുനിക സുരക്ഷാ സൗകര്യം",
    feat_subtitle: "പർവ്വത മേഖലകളിൽ സഞ്ചാരികളുടെ സുരക്ഷ ഉറപ്പാക്കുന്ന സാങ്കേതികവിദ്യ.",
    feat_1_title: "ബ്ലോക്ക്ചെയിൻ ഡിജിറ്റൽ ഐഡി",
    feat_1_desc: "SHA-256 വഴി സുരക്ഷിതമായ ഡിജിറ്റൽ തിരിച്ചറിയൽ രേഖ.",
    feat_2_title: "AI വോയ്‌സ് അസിസ്റ്റന്റ്",
    feat_2_desc: "12+ ഭാഷകളിൽ 15 സെക്കൻഡ് അടിയന്തിര ശബ്ദ സഹായം.",
    feat_3_title: "ഡിജിറ്റൽ ട്വിൻ റിസ്ക് വിശകലനം",
    feat_3_desc: "കാലാവസ്ഥയും ഉയരവും വിശകലനം ചെയ്യുന്ന തത്സമയ സംവിധാനം.",
    feat_4_title: "ജിയോഫെൻസിംഗ് മുന്നറിയിപ്പ്",
    feat_4_desc: "അപകട മേഖലകളിൽ പ്രവേശിക്കുമ്പോൾ സ്വയം പ്രവർത്തിക്കുന്ന മുന്നറിയിപ്പ്.",
    feat_5_title: "തത്സമയ രക്ഷാപ്രവർത്തനം",
    feat_5_desc: "സിക്കിം പൊലീസുമായും കൺട്രോൾ റൂമുമായും നേരിട്ടുള്ള ബന്ധം.",
    feat_6_title: "ഓഫ്‌ലൈൻ SMS മുന്നറിയിപ്പ്",
    feat_6_desc: "നെറ്റ്‌വർക്ക് ഇല്ലാത്ത സ്ഥലങ്ങളിൽ സാറ്റലൈറ്റ് വഴി SMS മുന്നറിയിപ്പ്.",
    hiw_tag: "ലളിതമായ പ്രക്രിയ",
    hiw_title: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    hiw_subtitle: "സിക്കിം യാത്രയ്ക്ക് മുൻപ് 4 ലളിതമായ ഘട്ടങ്ങളിലൂടെ സുരക്ഷ ഉറപ്പാക്കൂ.",
    hiw_1_title: "1. ഡിജിറ്റൽ ഐഡി ഉണ്ടാക്കൂ",
    hiw_1_desc: "നിങ്ങളുടെ സുരക്ഷിത QR കോഡ് ഐഡി ലഭിക്കാൻ വിവരങ്ങൾ നൽകൂ.",
    hiw_2_title: "2. ലൈവ് ട്രാക്കിംഗ് ഓൺ ചെയ്യൂ",
    hiw_2_desc: "യാത്രാ റൂട്ട് പങ്കുവെച്ച് ലൈവ് ലൊക്കേഷൻ ഓൺ ചെയ്യൂ.",
    hiw_3_title: "3. സ്മാർട്ട് മുന്നറിയിപ്പുകൾ ലഭിക്കൂ",
    hiw_3_desc: "കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ ഉടൻ തന്നെ ലഭിക്കും.",
    hiw_4_title: "4. വൺ-ടാപ്പ് അടിയന്തിര SOS",
    hiw_4_desc: "തത്സമയ സഹായത്തിനായി SOS ബട്ടൺ അമർത്തൂ.",
    emer_banner_title: "നിങ്ങൾ ഇപ്പോൾ അടിയന്തിര സാഹചര്യത്തിലാണോ?",
    emer_banner_subtitle: "ഉടൻ തന്നെ SOS ബട്ടൺ അമർത്തുക അല്ലെങ്കിൽ ദേശീയ ഹെൽപ്പ് ലൈനിൽ വിളിക്കുക.",
    emer_btn_sos: "അടിയന്തിര SOS പ്രവർത്തിപ്പിക്കുക",
    emer_btn_call: "112 ദേശീയ ഹെൽപ്പ് ലൈനിൽ വിളിക്കുക",
    lang_tag: "ഭാഷകൾ",
    lang_title: "പിന്തുണയ്ക്കുന്ന ഭാഷകൾ",
    lang_subtitle: "നിങ്ങളുടെ മാതൃഭാഷയിൽ സുരക്ഷാ സേവനങ്ങൾ നേടൂ. മാറ്റാൻ താഴെ ക്ലിക്ക് ചെയ്യൂ.",
    dig_title: "ഡിജിറ്റൽ ടൂറിസ്റ്റ് ഐഡി",
    dig_subtitle: "ചെക്ക്-പോസ്റ്റുകളിൽ വേഗത്തിലുള്ള പരിശോധനയ്ക്ക് ബ്ലോക്ക്ചെയിൻ ഐഡി.",
    dig_gen_id: "ഡിജിറ്റൽ ഐഡി നിർമ്മിക്കുക",
    dig_qr_status: "QR അവസ്ഥ: സജീവം, പരിശോധിച്ചു ഉറപ്പാക്കിയത്",
    dig_verified: "ബ്ലോക്ക്ചെയിൻ വഴി സാക്ഷ്യപ്പെടുത്തിയത്",
    dig_form_name: "പൂർണ്ണമായ പേര്",
    dig_form_phone: "മൊബൈൽ നമ്പർ",
    dig_form_passport: "സർക്കാർ ഐഡി / പാസ്‌പോർട്ട് / ആധാർ നമ്പർ",
    dig_form_submit: "ബ്ലോക്ക്ചെയിൻ ഐഡി നിർമ്മിക്കുക",
    tr_title: "ലൈവ് GPS & സുരക്ഷാ അവസ്ഥ",
    tr_subtitle: "തത്സമയ ലൊക്കേഷൻ നിരീക്ഷണവും ജിയോഫെൻസ് അവസ്ഥയും.",
    tr_status_active: "ട്രാക്കിംഗ് അവസ്ഥ: സജീവം",
    tr_status_safe: "നിലവിലെ മേഖല: സുരക്ഷിത മേഖല (ഗാംഗ്‌ടോക്)",
    tr_geofence_status: "ജിയോഫെൻസ് അവസ്ഥ: അനുവദിച്ച വഴിയിൽ തന്നെ",
    tr_battery: "ബാറ്ററി ലെവൽ: 88%",
    saf_title: "സുരക്ഷാ നിർദ്ദേശങ്ങൾ",
    saf_subtitle: "മലയോര യാത്രകൾക്ക് ആവശ്യമായ മുൻകരുതലുകൾ.",
    saf_weather_advisory: "കാലാവസ്ഥാ മുന്നറിയിപ്പ്: വടക്കൻ സിക്കിമിൽ ശക്തമായ മഴ മുന്നറിയിപ്പ്.",
    saf_altitude_tip: "ഉയരമുള്ള സ്ഥലങ്ങളിലെ ഉപദേശം: നാഥുല പാസിലേക്ക് പോകും മുൻപ് ഗാംഗ്‌ടോക്കിൽ വിശ്രമിക്കുക.",
    saf_emergency_contact: "ലോക്കൽ എമർജൻസി കൺട്രോൾ സെന്റർ: +91 03592 202022",
    sos_title: "അടിയന്തിര SOS അയക്കൽ",
    sos_subtitle: "AI വോയ്‌സ് സഹായത്തോടെ ഉടനടി രക്ഷാസംഘത്തെ അയക്കുന്നു.",
    sos_trigger_btn: "അടിയന്തിര SOS-നായി അമർത്തുക",
    sos_status_connecting: "എമർജൻസി സെന്ററുമായി ബന്ധപ്പെടുന്നു...",
    sos_helpline_112: "ദേശീയ അടിയന്തിര ഹെൽപ്പ് ലൈൻ: 112",
    faq_title: "പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ",
    faq_subtitle: "സുരക്ഷയെക്കുറിച്ചും ഡിജിറ്റൽ ഐഡിയെക്കുറിച്ചുമുള്ള ഉത്തരങ്ങൾ കണ്ടെത്തൂ.",
    faq_search_placeholder: "ചോദ്യങ്ങൾ തിരയുക...",
    login_title: "അതോറിറ്റി ലോഗിൻ",
    login_subtitle: "സിക്കിം സുരക്ഷാ നിരീക്ഷണ ഡാഷ്‌ബോർഡ് പ്രവേശിക്കുക",
    reg_title: "ടൂറിസ്റ്റ് രജിസ്ട്രേഷൻ",
    reg_subtitle: "നിങ്ങളുടെ ഡിജിറ്റൽ സുരക്ഷാ പ്രൊഫൈൽ ഉണ്ടാക്കൂ",
    foot_title: "സിക്കിം സ്മാർട്ട് സുരക്ഷ",
    foot_desc: "അത്യാധുനിക AI സാങ്കേതികവിദ്യ ഉപയോഗിച്ച് സുരക്ഷിതമായ ടൂറിസം ഉറപ്പാക്കുന്നു.",
    foot_copy: "ടൂറിസം മന്ത്രാലയം, ഭാരത സർക്കാർ. എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം.",
    foot_links_header: "ദ്രുത ലിങ്കുകൾ",
    foot_emer_header: "അടിയന്തിര ബന്ധപ്പെടൽ"
  },
  or: {
    nav_about: "ଆମ ବିଷୟରେ",
    nav_digital_id: "ଡିଜିଟାଲ୍ ଆଇଡି",
    nav_my_tracking: "ମୋର ଟ୍ରାକିଂ",
    nav_safety: "ସୁରକ୍ଷା ପରାମର୍ଶ",
    nav_emergency: "ଜରୁରୀକାଳୀନ SOS",
    nav_faq: "ସାଧାରଣ ପ୍ରଶ୍ନ",
    nav_register: "ପଞ୍ଜୀକରଣ",
    nav_login: "କର୍ତ୍ତୃପକ୍ଷ ଲଗଇନ୍",
    nav_dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    nav_logout: "ଲଗଆଉଟ୍",
    hero_badge: "ପର୍ଯ୍ୟଟନ ମନ୍ତ୍ରଣାଳୟ • ଭାରତ ସରକାର",
    hero_title: "ସ୍ମାର୍ଟ ପର୍ଯ୍ୟଟକ ସୁରକ୍ଷା ବ୍ୟବସ୍ଥା",
    hero_subtitle: "ସିକିମରେ ରିଅଲ-ଟାଇମ୍ ସୁରକ୍ଷା ନିରୀକ୍ଷଣ ଏବଂ ସୁରକ୍ଷିତ ବ୍ଲକଚେନ୍ ପର୍ଯ୍ୟଟକ ପରିଚୟ।",
    hero_register: "ପର୍ଯ୍ୟଟକ ଆଇଡି ପଞ୍ଜୀକରଣ",
    hero_login: "କର୍ତ୍ତୃପକ୍ଷ ପ୍ରବେଶ",
    stat_tourists: "ସୁରକ୍ଷିତ ପର୍ଯ୍ୟଟକ",
    stat_monitoring: "ଲାଇଭ୍ ନିରୀକ୍ଷଣ",
    stat_zones: "ସୁରକ୍ଷିତ ଅଞ୍ଚଳ",
    stat_response: "ହାରାହାରି ପ୍ରତିକ୍ରିୟା ସମୟ",
    feat_tag: "ମୁଖ୍ୟ ବୈଶିଷ୍ଟ୍ୟ",
    feat_title: "ଉନ୍ନତ ସୁରକ୍ଷା ଭିତ୍ତିଭୂମି",
    feat_subtitle: "ପାର୍ବତ୍ୟ ଅଞ୍ଚଳରେ ପର୍ଯ୍ୟଟକଙ୍କ ସୁରକ୍ଷା ସୁନିଶ୍ଚିତ କରୁଥିବା ବୈଷୟିକ ଜ୍ଞାନକୌଶଳ।",
    feat_1_title: "ବ୍ଲକଚେନ୍ ଡିଜିଟାଲ୍ ଆଇଡି",
    feat_1_desc: "SHA-256 ଦ୍ୱାରା ସୁରକ୍ଷିତ ଏବଂ ଯାଞ୍ଚ ହୋଇଥିବା ଡିଜିଟାଲ୍ ପରିଚୟ।",
    feat_2_title: "AI ଭଏସ୍ ଆସିଷ୍ଟାଣ୍ଟ",
    feat_2_desc: "୧୨+ ଭାଷାରେ ୧୫ ସେକେଣ୍ଡର ଜରୁରୀକାଳୀନ ଭଏସ୍ ସହାୟତା।",
    feat_3_title: "ଡିଜିଟାଲ୍ ଟ୍ୱିନ୍ ଆକଳନ",
    feat_3_desc: "ପାଣିପାଗ ଏବଂ ବିପଦର ରିଅଲ-ଟାଇମ୍ ବିଶ୍ଳେଷଣ।",
    feat_4_title: "ଜିଓଫେନ୍ସିଂ ସତର୍କତା",
    feat_4_desc: "ବିପଜ୍ଜନକ ଅଞ୍ଚଳକୁ ଗଲେ ସ୍ୱୟଂଚାଳିତ ଆଲର୍ଟ।",
    feat_5_title: "ତୁରନ୍ତ ଉଦ୍ଧାର ପ୍ରତିକ୍ରିୟା",
    feat_5_desc: "ସିକିମ୍ ପୋଲିସ୍ ଏବଂ ନିୟନ୍ତ୍ରଣ କକ୍ଷ ସହିତ ସିଧାସଳଖ ସଂଯୋଗ।",
    feat_6_title: "ଅଫଲାଇନ୍ SMS ଆଲର୍ଟ",
    feat_6_desc: "ନେଟୱର୍କ ନଥିଲେ ସାଟେଲାଇଟ୍ ଏବଂ SMS ଆଲର୍ଟ।",
    hiw_tag: "ସରଳ ପ୍ରକ୍ରିୟା",
    hiw_title: "ଏହା କିପରି କାମ କରେ",
    hiw_subtitle: "ସିକିମ୍ ଭ୍ରମଣ ପୂର୍ବରୁ ୪ଟି ସହଜ ସୋପାନରେ ସୁରକ୍ଷା ପାଆନ୍ତୁ।",
    hiw_1_title: "୧. ଡିଜିଟାଲ୍ ଆଇଡି ତିଆରି କରନ୍ତୁ",
    hiw_1_desc: "ଆପଣଙ୍କ ସୁରକ୍ଷିତ QR କୋଡ୍ ଆଇଡି ପାଇଁ ତଥ୍ୟ ଦିଅନ୍ତୁ।",
    hiw_2_title: "୨. ଲାଇଭ୍ ଟ୍ରାକିଂ ଅନ୍ କରନ୍ତୁ",
    hiw_2_desc: "ଆପଣଙ୍କ ରୁଟ୍ ସେୟାର୍ କରନ୍ତୁ ଏବଂ ଲାଇଭ୍ ଲୋକେସନ୍ ଅନ୍ କରନ୍ତୁ।",
    hiw_3_title: "୩. ସ୍ମାର୍ଟ ସତର୍କତା ପାଆନ୍ତୁ",
    hiw_3_desc: "ପାଣିପାଗ ଏବଂ ସୀମା ସତର୍କତା ତୁରନ୍ତ ପାଆନ୍ତୁ।",
    hiw_4_title: "୪. ୱାନ୍-ଟାପ୍ ଜରୁରୀ SOS",
    hiw_4_desc: "ତୁରନ୍ତ ସହାୟତା ପାଇଁ SOS ବଟନ୍ ଦବାନ୍ତୁ।",
    emer_banner_title: "ଆପଣ ଏବେ କୌଣସି ଜରୁରୀ ପରିସ୍ଥିତିରେ ଅଛନ୍ତି କି?",
    emer_banner_subtitle: "ତୁରନ୍ତ SOS ବଟନ୍ ଦବାନ୍ତୁ କିମ୍ବା ଜାତୀୟ ହେଲ୍ପଲାଇନ୍ ନମ୍ବରକୁ କଲ୍ କରନ୍ତୁ।",
    emer_btn_sos: "ଜରୁରୀ SOS ସକ୍ରିୟ କରନ୍ତୁ",
    emer_btn_call: "୧୧୨ ଜାତୀୟ ହେଲ୍ପଲାଇନକୁ କଲ୍ କରନ୍ତୁ",
    lang_tag: "ଭାଷା",
    lang_title: "ସମର୍ଥିତ ଭାଷାସମୂହ",
    lang_subtitle: "ଆପଣଙ୍କ ମାତୃଭାଷାରେ ସୁରକ୍ଷା ସେବା ପାଆନ୍ତୁ। ବଦଳାଇବା ପାଇଁ ତଳେ କ୍ଲିକ୍ କରନ୍ତୁ।",
    dig_title: "ଡିଜିଟାଲ୍ ପର୍ଯ୍ୟଟକ ଆଇଡି",
    dig_subtitle: "ଚେକ୍-ପୋଷ୍ଟରେ ଦ୍ରୁତ ଯାଞ୍ଚ ପାଇଁ ବ୍ଲକଚେନ୍ ପରିଚୟ ପତ୍ର।",
    dig_gen_id: "ଡିଜିଟାଲ୍ ଆଇଡି ସୃଷ୍ଟି କରନ୍ତୁ",
    dig_qr_status: "QR ସ୍ଥିତି: ସକ୍ରିୟ ଏବଂ ସତ୍ୟାପିତ",
    dig_verified: "ବ୍ଲକଚେନ୍ ଦ୍ୱାରା ସତ୍ୟାପିତ",
    dig_form_name: "ପୂରା ନାମ",
    dig_form_phone: "ମୋବାଇଲ୍ ନମ୍ବର",
    dig_form_passport: "ସରକାରୀ ଆଇଡି / ପାସପୋର୍ଟ / ଆଧାର ନମ୍ବର",
    dig_form_submit: "ବ୍ଲକଚେନ୍ ଆଇଡି ତିଆରି କରନ୍ତୁ",
    tr_title: "ଲାଇଭ୍ GPS ଏବଂ ସୁରକ୍ଷା ସ୍ଥିତି",
    tr_subtitle: "ରିଅଲ-ଟାଇମ୍ ସ୍ଥାନ ନିରୀକ୍ଷଣ ଏବଂ ଜିଓଫେନ୍ସ ସ୍ଥିତି।",
    tr_status_active: "ଟ୍ରାକିଂ ସ୍ଥିତି: ସକ୍ରିୟ",
    tr_status_safe: "ବର୍ତ୍ତମାନ ଅଞ୍ଚଳ: ସୁରକ୍ଷିତ ଅଞ୍ଚଳ (ଗାଙ୍ଗଟକ୍)",
    tr_geofence_status: "ଜିଓଫେନ୍ସ ସ୍ଥିତି: ଅନୁମୋଦିତ ରୁଟ୍ ଭିତରେ",
    tr_battery: "ବ୍ୟାଟେରୀ ସ୍ତର: ୮୮%",
    saf_title: "ସୁରକ୍ଷା ପରାମର୍ଶ",
    saf_subtitle: "ପାର୍ବତ୍ୟ ଭ୍ରମଣ ପାଇଁ ଆବଶ୍ୟକୀୟ ସାବଧାନତା।",
    saf_weather_advisory: "ପାଣିପାଗ ସୂଚନା: ଉତ୍ତର ସିକିମରେ ପ୍ରବଳ ବର୍ଷା ସମ୍ଭାବନା।",
    saf_altitude_tip: "ଉଚ୍ଚ ସ୍ଥାନ ପରାମର୍ଶ: ନାଥୁଲା ପାସ୍ ଯିବା ପୂର୍ବରୁ ଗାଙ୍ଗଟକରେ ବିଶ୍ରାମ ନିଅନ୍ତୁ।",
    saf_emergency_contact: "ସ୍ଥାନୀୟ ଜରୁରୀ କମାଣ୍ଡ ସେଣ୍ଟର: +91 03592 202022",
    sos_title: "ଜରୁରୀ SOS ପ୍ରେରଣ",
    sos_subtitle: "AI ଭଏସ୍ ସହାୟତା ସହିତ ତୁରନ୍ତ ଉଦ୍ଧାରକାରୀ ଦଳ ପଠାଇବା।",
    sos_trigger_btn: "ଜରୁରୀ SOS ପାଇଁ ଦବାନ୍ତୁ",
    sos_status_connecting: "ଜରୁରୀ କେନ୍ଦ୍ର ସହିତ ସଂଯୋଗ ହେଉଛି...",
    sos_helpline_112: "ଜାତୀୟ ଜରୁରୀ ହେଲ୍ପଲାଇନ୍: ୧୧୨",
    faq_title: "ସାଧାରଣ ପ୍ରଶ୍ନୋତ୍ତର",
    faq_subtitle: "ସୁରକ୍ଷା ଏବଂ ଡିଜିଟାଲ୍ ଆଇଡି ବିଷୟରେ ଉତ୍ତର ଖୋଜନ୍ତୁ।",
    faq_search_placeholder: "ପ୍ରଶ୍ନ ଖୋଜନ୍ତୁ...",
    login_title: "କର୍ତ୍ତୃପକ୍ଷ ଲଗଇନ୍",
    login_subtitle: "ସିକିମ୍ ସୁରକ୍ଷା ନିରୀକ୍ଷଣ ଡ୍ୟାସବୋର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ",
    reg_title: "ପର୍ଯ୍ୟଟକ ପଞ୍ଜୀକରଣ",
    reg_subtitle: "ଆପଣଙ୍କ ଡିଜିଟାଲ୍ ସୁରକ୍ଷା ପ୍ରୋଫାଇଲ୍ ତିଆରି କରନ୍ତୁ",
    foot_title: "ସିକିମ୍ ସ୍ମାର୍ଟ ସୁରକ୍ଷା",
    foot_desc: "ଉନ୍ନତ AI ବୈଷୟିକ ଜ୍ଞାନକୌଶଳ ସହିତ ସୁରକ୍ଷିତ ପର୍ଯ୍ୟଟନ ସୁନିଶ୍ଚିତ କରିବା।",
    foot_copy: "ପର୍ଯ୍ୟଟନ ମନ୍ତ୍ରଣାଳୟ, ଭାରତ ସରକାର। ସର୍ବସ୍ୱତ୍ୱ ସଂରକ୍ଷିତ।",
    foot_links_header: "ଦ୍ରୁତ ଲିଙ୍କ୍",
    foot_emer_header: "ଜରୁରୀ ଯୋଗାଯୋଗ"
  },
  pa: {
    nav_about: "ਬਾਰੇ",
    nav_digital_id: "ਡਿਜੀਟਲ ਆਈਡੀ",
    nav_my_tracking: "ਮੇਰੀ ਟ੍ਰੈਕਿੰਗ",
    nav_safety: "ਸੁਰੱਖਿਆ ਸੁਝਾਅ",
    nav_emergency: "ਐਮਰਜੈਂਸੀ SOS",
    nav_faq: "ਸਵਾਲ ਜਵਾਬ",
    nav_register: "ਰਜਿਸਟਰ ਕਰੋ",
    nav_login: "ਅਧਿਕਾਰੀ ਲੌਗਇਨ",
    nav_dashboard: "ਡੈਸ਼ਬੋਰਡ",
    nav_logout: "ਲੌਗਆਉਟ",
    hero_badge: "ਟੂਰਿਜ਼ਮ ਮੰਤਰਾਲਾ • ਭਾਰਤ ਸਰਕਾਰ",
    hero_title: "ਸਮਾਰਟ ਸੈਲਾਨੀ ਸੁਰੱਖਿਆ ਪ੍ਰਣਾਲੀ",
    hero_subtitle: "ਸਿੱਕਮ ਵਿੱਚ ਰੀਅਲ-ਟਾਈਮ ਸੁਰੱਖਿਆ ਨਿਗਰਾਨੀ ਅਤੇ ਸੁਰੱਖਿਅਤ ਬਲਾਕਚੇਨ ਸੈਲਾਨੀ ਪਛਾਣ।",
    hero_register: "ਸੈਲਾਨੀ ਆਈਡੀ ਰਜਿਸਟਰ ਕਰੋ",
    hero_login: "ਅਧਿਕਾਰੀ ਪਹੁੰਚ",
    stat_tourists: "ਸੁਰੱਖਿਅਤ ਸੈਲਾਨੀ",
    stat_monitoring: "ਲਾਈਵ ਨਿਗਰਾਨੀ",
    stat_zones: "ਸੁਰੱਖਿਅਤ ਖੇਤਰ",
    stat_response: "ਔਸਤ ਪ੍ਰਤੀਕਿਰਿਆ ਸਮਾਂ",
    feat_tag: "ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    feat_title: "ਉੱਨਤ ਸੁਰੱਖਿਆ ਢਾਂਚਾ",
    feat_subtitle: "ਖਤਰਨਾਕ ਪਹਾੜੀ ਖੇਤਰਾਂ ਵਿੱਚ ਸੈਲਾਨੀਆਂ ਦੀ ਸੁਰੱਖਿਆ ਯਕੀਨੀ ਬਣਾਉਣ ਵਾਲੀ ਤਕਨਾਲੋਜੀ।",
    feat_1_title: "ਬਲਾਕਚੇਨ ਡਿਜੀਟਲ ਆਈਡੀ",
    feat_1_desc: "SHA-256 ਰਾਹੀਂ ਸੁਰੱਖਿਅਤ ਅਤੇ ਪ੍ਰਮਾਣਿਤ ਡਿਜੀਟਲ ਪਛਾਣ।",
    feat_2_title: "AI ਵੌਇਸ ਅਸਿਸਟੈਂਟ",
    feat_2_desc: "12+ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ 15-ਸਕਿੰਟ ਦੀ ਐਮਰਜੈਂਸੀ ਵੌਇਸ ਸਹਾਇਤਾ।",
    feat_3_title: "ਡਿਜੀਟਲ ਟਵਿਨ ਜੋਖਮ ਮੁਲਾਂਕਣ",
    feat_3_desc: "ਮੌਸਮ ਅਤੇ ਉਚਾਈ ਦੇ ਖਤਰਿਆਂ ਦਾ ਰੀਅਲ-ਟਾਈਮ ਵਿਸ਼ਲੇਸ਼ਣ।",
    feat_4_title: "ਜੀਓਫੈਂਸਿੰਗ ਚੇਤਾਵਨੀਆਂ",
    feat_4_desc: "ਖਤਰਨਾਕ ਖੇਤਰਾਂ ਵਿੱਚ ਦਾਖਲ ਹੋਣ 'ਤੇ ਸਵੈਚਲਿਤ ਅਲਰਟ।",
    feat_5_title: "ਤੁਰੰਤ ਬਚਾਅ ਪ੍ਰਤੀਕਿਰਿਆ",
    feat_5_desc: "ਸਿੱਕਮ ਪੁਲਿਸ ਅਤੇ ਕੰਟਰੋਲ ਰੂਮ ਨਾਲ ਸਿੱਧਾ ਸੰਪਰਕ।",
    feat_6_title: "ਆਫਲਾਈਨ SMS ਅਲਰਟ",
    feat_6_desc: "ਨੈੱਟਵਰਕ ਨਾ ਹੋਣ 'ਤੇ ਸੈਟੇਲਾਈਟ ਅਤੇ ਮੈਸ਼ SMS ਅਲਰਟ।",
    hiw_tag: "ਸਰਲ ਪ੍ਰਕਿਰਿਆ",
    hiw_title: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
    hiw_subtitle: "ਸਿੱਕਮ ਯਾਤਰਾ ਤੋਂ ਪਹਿਲਾਂ 4 ਆਸਾਨ ਕਦਮਾਂ ਵਿੱਚ ਸੁਰੱਖਿਆ ਪ੍ਰਾਪਤ ਕਰੋ।",
    hiw_1_title: "1. ਡਿਜੀਟਲ ਆਈਡੀ ਬਣਾਓ",
    hiw_1_desc: "ਆਪਣਾ ਸੁਰੱਖਿਅਤ QR ਕੋਡ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਵੇਰਵੇ ਦਿਓ।",
    hiw_2_title: "2. ਲਾਈਵ ਟ੍ਰੈਕਿੰਗ ਚਾਲੂ ਕਰੋ",
    hiw_2_desc: "ਆਪਣਾ ਰੂਟ ਸਾਂਝਾ ਕਰੋ ਅਤੇ ਲਾਈਵ ਲੋਕੇਸ਼ਨ ਆਨ ਕਰੋ।",
    hiw_3_title: "3. ਸਮਾਰਟ ਅਲਰਟ ਪ੍ਰਾਪਤ ਕਰੋ",
    hiw_3_desc: "ਮੌਸਮ ਅਤੇ ਸੀਮਾ ਚੇਤਾਵਨੀਆਂ ਤੁਰੰਤ ਪ੍ਰਾਪਤ ਕਰੋ।",
    hiw_4_title: "4. ਵਨ-ਟੈਪ ਐਮਰਜੈਂਸੀ SOS",
    hiw_4_desc: "ਤੁਰੰਤ ਮਦਦ ਲਈ SOS ਬਟਨ ਦਬਾਓ।",
    emer_banner_title: "ਕੀ ਤੁਸੀਂ ਹੁਣੇ ਕਿਸੇ ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਹੋ?",
    emer_banner_subtitle: "ਤੁਰੰਤ SOS ਬਟਨ ਦਬਾਓ ਜਾਂ ਰਾਸ਼ਟਰੀ ਐਮਰਜੈਂਸੀ ਹੈਲਪਲਾਈਨ 'ਤੇ ਕਾਲ ਕਰੋ।",
    emer_btn_sos: "ਐਮਰਜੈਂਸੀ SOS ਚਾਲੂ ਕਰੋ",
    emer_btn_call: "112 ਰਾਸ਼ਟਰੀ ਹੈਲਪਲਾਈਨ 'ਤੇ ਕਾਲ ਕਰੋ",
    lang_tag: "ਭਾਸ਼ਾਵਾਂ",
    lang_title: "ਸਮਰਥਿਤ ਭਾਸ਼ਾਵਾਂ",
    lang_subtitle: "ਆਪਣੀ ਮਾਂ-ਬੋਲੀ ਵਿੱਚ ਸੁਰੱਖਿਆ ਸੇਵਾਵਾਂ ਪ੍ਰਾਪਤ ਕਰੋ। ਬਦਲਣ ਲਈ ਹੇਠਾਂ ਕਲਿੱਕ ਕਰੋ।",
    dig_title: "ਡਿਜੀਟਲ ਸੈਲਾਨੀ ਆਈਡੀ",
    dig_subtitle: "ਚੈੱਕ-ਪੋਸਟਾਂ 'ਤੇ ਤੇਜ਼ ਜਾਂਚ ਲਈ ਬਲਾਕਚੇਨ ਪਛਾਣ ਪੱਤਰ।",
    dig_gen_id: "ਡਿਜੀਟਲ ਆਈਡੀ ਬਣਾਓ",
    dig_qr_status: "QR ਸਥਿਤੀ: ਸਰਗਰਮ ਅਤੇ ਪ੍ਰਮਾਣਿਤ",
    dig_verified: "ਬਲਾਕਚੇਨ ਦੁਆਰਾ ਪ੍ਰਮਾਣਿਤ",
    dig_form_name: "ਪੂਰਾ ਨਾਮ",
    dig_form_phone: "ਮੋਬਾਈਲ ਨੰਬਰ",
    dig_form_passport: "ਸਰਕਾਰੀ ਆਈਡੀ / ਪਾਸਪੋਰਟ / ਆਧਾਰ ਨੰਬਰ",
    dig_form_submit: "ਬਲਾਕਚੇਨ ਆਈਡੀ ਬਣਾਓ",
    tr_title: "ਲਾਈਵ GPS ਅਤੇ ਸੁਰੱਖਿਆ ਸਥਿਤੀ",
    tr_subtitle: "ਰੀਅਲ-ਟਾਈਮ ਲੋਕੇਸ਼ਨ ਨਿਗਰਾਨੀ ਅਤੇ ਜੀਓਫੈਂਸ ਸਥਿਤੀ।",
    tr_status_active: "ਟ੍ਰੈਕਿੰਗ ਸਥਿਤੀ: ਸਰਗਰਮ",
    tr_status_safe: "ਮੌਜੂਦਾ ਖੇਤਰ: ਸੁਰੱਖਿਅਤ ਖੇਤਰ (ਗੰਗਟੋਕ)",
    tr_geofence_status: "ਜੀਓਫੈਂਸ ਸਥਿਤੀ: ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਰੂਟ ਦੇ ਅੰਦਰ",
    tr_battery: "ਬੈਟਰੀ ਪੱਧਰ: 88%",
    saf_title: "ਸੁਰੱਖਿਆ ਸੁਝਾਅ",
    saf_subtitle: "ਪਹਾੜੀ ਯਾਤਰਾ ਲਈ ਜ਼ਰੂਰੀ ਸਾਵਧਾਨੀਆਂ।",
    saf_weather_advisory: "ਮੌਸਮ ਚੇਤਾਵਨੀ: ਉੱਤਰੀ ਸਿੱਕਮ ਵਿੱਚ ਭਾਰੀ ਮੀਂਹ ਦੀ ਚੇਤਾਵਨੀ।",
    saf_altitude_tip: "ਉਚਾਈ ਸੁਝਾਅ: ਨਾਥੂਲਾ ਪਾਸ ਜਾਣ ਤੋਂ ਪਹਿਲਾਂ ਗੰਗਟੋਕ ਵਿੱਚ ਆਰਾਮ ਕਰੋ।",
    saf_emergency_contact: "ਸਥਾਨਕ ਐਮਰਜੈਂਸੀ ਕੰਟਰੋਲ ਸੈਂਟਰ: +91 03592 202022",
    sos_title: "ਐਮਰਜੈਂਸੀ SOS ਭੇਜੋ",
    sos_subtitle: "AI ਵੌਇਸ ਮਦਦ ਨਾਲ ਤੁਰੰਤ ਬਚਾਅ ਟੀਮ ਭੇਜਣਾ।",
    sos_trigger_btn: "ਐਮਰਜੈਂਸੀ SOS ਲਈ ਦਬਾਓ",
    sos_status_connecting: "ਐਮਰਜੈਂਸੀ ਸੈਂਟਰ ਨਾਲ ਕਨੈਕਟ ਹੋ ਰਿਹਾ ਹੈ...",
    sos_helpline_112: "ਰਾਸ਼ਟਰੀ ਐਮਰਜੈਂਸੀ ਹੈਲਪਲਾਈਨ: 112",
    faq_title: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
    faq_subtitle: "ਸੁਰੱਖਿਆ ਅਤੇ ਡਿਜੀਟਲ ਆਈਡੀ ਬਾਰੇ ਜਵਾਬ ਲੱਭੋ।",
    faq_search_placeholder: "ਸਵਾਲ ਖੋਜੋ...",
    login_title: "ਅਧਿਕਾਰੀ ਲੌਗਇਨ",
    login_subtitle: "ਸਿੱਕਮ ਸੁਰੱਖਿਆ ਨਿਗਰਾਨੀ ਡੈਸ਼ਬੋਰਡ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ",
    reg_title: "ਸੈਲਾਨੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    reg_subtitle: "ਆਪਣੀ ਡਿਜੀਟਲ ਸੁਰੱਖਿਆ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ",
    foot_title: "ਸਿੱਕਮ ਸਮਾਰਟ ਸੁਰੱਖਿਆ",
    foot_desc: "ਉੱਨਤ AI ਤਕਨਾਲੋਜੀ ਨਾਲ ਸੁਰੱਖਿਅਤ ਸੈਰ-ਸਪਾਟਾ ਯਕੀਨੀ ਬਣਾਉਣਾ।",
    foot_copy: "ਟੂਰਿਜ਼ਮ ਮੰਤਰਾਲਾ, ਭਾਰਤ ਸਰਕਾਰ। ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।",
    foot_links_header: "ਤੁਰੰਤ ਲਿੰਕ",
    foot_emer_header: "ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ"
  }
};

interface LanguageContextProps {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLocale = localStorage.getItem("app_locale") as Locale;
    if (savedLocale && SUPPORTED_LOCALES.some(l => l.code === savedLocale)) {
      setLocaleState(savedLocale);
    }
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem("app_locale", newLocale);
  };

  const t = (key: string): string => {
    const dictionary = TRANSLATIONS[locale];
    if (dictionary && dictionary[key]) {
      return dictionary[key];
    }
    // Fallback to English
    const fallbackDict = TRANSLATIONS["en"];
    return (fallbackDict && fallbackDict[key]) || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

